//! DeepSeek-V4's prompt encoding — a hand-port of `encoding/encoding_dsv4.py`, which ships
//! **inside the checkpoint** at `/var/db/rivoli/deepseek-v4-flash-0731/encoding/`.
//!
//! Ported from `old:src/artifact/dsv4_encoding.rs` (`wt/glimmer-s2` @ 6b7f496), bodies and
//! comments travelling verbatim: in this repo a comment carries the measurement that justified
//! the choice, so a re-worded one loses evidence.
//!
//! > **RENAMED IN THE PORT, 2026-08-16, and the reference's own argument is why the rename is
//! > allowed.** There the file is `dsv4_encoding.rs` and its header cites "even the filename
//! > mirrors the script it ports" as one of three reasons the name is model-bound. Two of the
//! > three still hold verbatim below — the control tokens are this model's own and the module is
//! > gated byte-for-byte against the checkpoint's gold vectors — but the third cannot: this is a
//! > module of **four** files (root, `message`, `render`, `parse`), and no one of them mirrors
//! > `encoding_dsv4.py`. What replaces it is the tree's own spelling: `V4Config`,
//! > `v4_expert_base`, `V4_PROJ`, `F4_NAMING_V4` and `crates/artifact/src/v4_config.rs` all say
//! > `v4`, and a fifth spelling for the same checkpoint is a grep that misses. The module stays
//! > model-bound; only the prefix follows the neighbours.
//!
//! Model-bound by construction (category (b) of the 2026-08-09 rename pass): the emitted
//! control tokens are this model's own and the module is gated byte-for-byte against the
//! checkpoint's gold vectors. GLM's equivalent is
//! [`crate::tokenizer::Tokenizer::encode_chat_turns`] and Muse Glimmer's is
//! [`crate::glimmer_encoding`] — the three must not converge. V4 and Glimmer both render a
//! **string** that is tokenized afterwards, where GLM builds a token-ID list; that shared shape
//! is a coincidence of two checkpoints, not a contract, and the only thing they share is
//! [`crate::tokenizer`]'s `python_json`/`json_truthy` pair.
//!
//! **This checkpoint has no `chat_template.jinja`, and that is deliberate.** Its README:
//!
//! > This release does not include a Jinja-format chat template. Instead, we provide a
//! > dedicated `encoding` folder with Python scripts and test cases demonstrating how to
//! > encode messages in OpenAI-compatible format into input strings for the model, and how
//! > to parse the model's text output.
//!
//! So there is nothing to load at runtime and no way to be *told* the framing is wrong. The
//! first V4 decode fed raw text to the model and got
//! `"The sky is blue because of Rayleigh scattering."` three times over — which is correct
//! **base-model** behaviour: outside an assistant turn the model is doing document
//! continuation and has no reason to emit `<｜end▁of▁sentence｜>`, so it ran to `-bench`.
//! EOS handling was never the bug.
//!
//! ## Why this file is gated on the reference's own vectors
//!
//! This repo has already been burned by exactly this. GLM's chat template lives only in the
//! fp8 SOURCE, `tokenizer::Tokenizer::encode_chat_turns` hand-ports it, and that port sat on
//! GLM-4's `<|role|>\n` framing **for months** before anyone noticed — because a
//! wrongly-framed prompt still produces fluent text. A wrong port here is silent and
//! invalidates every downstream quality number.
//!
//! Two gates, and the second exists because the first was demonstrably not enough:
//!
//! 1. the four gold files the checkpoint ships (`encoding/tests/test_output_{1,2,3,4}.txt`),
//!    byte-for-byte — `crates/artifact/tests/v4_encoding_gold.rs`, which skips (loudly, and
//!    failing on an explicitly-set env var that does not resolve) without the checkpoint;
//! 2. the unit tests under [`tests`], whose expectations were **generated by running
//!    `encoding_dsv4.py`**, never by reading the README. They are hermetic, so a machine with
//!    no `/var/db/rivoli/deepseek-v4-flash-0731` is not left with nothing — which is why a few
//!    of them deliberately re-cover ground the gold vectors already hold.
//!
//! > **PORT NOTE 2026-08-16: the reference has a THIRD gate and it is NOT ported.**
//! > `old:tests/v4_encoding.rs::differential_against_the_reference` drives
//! > `encoding_dsv4.py` and this module from one corpus (13 seeded adversarial conversations,
//! > then 600 from a fixed LCG) and diffs the strings. It is the strongest of the three and it
//! > earned its place: review on 2026-08-05 found a real divergence in
//! > `sort_tool_results_by_call_order` that all four golds and sixteen unit tests passed over.
//! >
//! > It is deferred rather than dropped, with an owner: it needs `tests/dsv4_reference_driver.py`
//! > vendored, a Python process, and ~190 lines of harness, and this tree has no precedent for a
//! > Python-driving test outside the anchor scripts (which take a pinned venv and a
//! > regeneration shell script, not a `cargo test`). **What makes the gap narrower than it
//! > sounds:** the divergence it caught is now pinned directly, by the `no_id` and `dup_id`
//! > cases in `tests::encode`'s `tool_results_merge_into_the_user_turn`, and this port is a
//! > transliteration of code that gate already validated — the failure class here is
//! > transcription, which the golds and the unit tests do catch. It belongs with the V4 engine
//! > task, beside the anchor work that already owns a pinned Python environment.
//!
//! Where the README and the code disagree the code wins; where this port and the reference
//! disagree, this port is wrong.
//!
//! ## Deliberate divergences, each with its reason
//!
//! - **`context` is not ported.** `encode_messages(context=…)` exists for prefix-caching a
//!   already-encoded conversation head. Nothing here caches prompts, and the parameter's
//!   interaction with `drop_thinking` (a second `_drop_thinking_messages` pass used only to
//!   recompute a slice offset) is the fiddliest code in the reference. Ported as
//!   `context = []`, which is what all four of the reference's own test cases pass.
//! - **A user turn's blocks are only the two kinds `merge_tool_messages` can produce.** The
//!   reference's `[Unsupported {type}]` fallback for a user `content_blocks` entry is dead:
//!   every path into `render_message` goes through `merge_tool_messages`, which *discards*
//!   any caller-supplied `content_blocks` and rebuilds them from `content`. (Confirmed by
//!   running it: a user message with an `image` block encodes to an empty user turn.) The
//!   same fallback inside a *tool result's* content list IS reachable, and is ported — in
//!   `tool_content`, at the boundary, since nothing downstream inspects the structure.
//! - **`direct_search_results`** appears in `_drop_thinking_messages`'s keep-list and in no
//!   other line of the reference; `render_message` would raise `NotImplementedError` on it.
//!   Not modelled.
//! - **The `role: "assistant"` key on the parser's return value** is a constant in the
//!   reference. Here it is the type of [`ParsedMessage`].
//! - **Null `content` renders as `""`, where the reference sometimes writes `None`.**
//!   `system` and `assistant` get a `content or ""` there and agree with this port —
//!   `assistant` matters, because `content: null` beside `tool_calls` is the ordinary OpenAI
//!   shape. `latest_reminder` and `tool` have no such guard, so a null formats Python's
//!   `None` straight into the prompt; that is a formatting slip, not a sequence the model was
//!   trained on. `user` is the third case and it RAISES there, so it raises here too.
//! - **Where the reference RAISES, this refuses too — at the BOUNDARY**, so the failure
//!   names the message index instead of surfacing halfway through a prompt: a non-string
//!   `content`, a null `content` on a `user` turn, an absent `function.arguments`, a `text`
//!   block whose `text` is null or not a string, a `tool` content block that is not an
//!   object, and a `task` — string or not — outside the six, on a message where the
//!   reference reaches its assert.
//!
//!   One case runs the other way and is recorded rather than fixed: a malformed `tool_calls`
//!   on a role that cannot render them (`system`, `latest_reminder`) is a `KeyError` there,
//!   because `tool_calls_from_openai_format` runs before the role dispatch, and is accepted
//!   here because only the assistant arm parses the key. No well-formed request reaches it.
//! - **OpenAI's array-of-parts `content` is ACCEPTED**, flattened through the reference's own
//!   `content_blocks` rule. It is standard in their schema and clients send it constantly.
//!   Precisely: on a `user` turn the reference raises TypeError, so there are no bytes and
//!   this fills a hole; on `system`/`developer`/`assistant` it emits a deterministic Python
//!   list repr and this **deliberately contradicts it**, because a list repr is not a
//!   sequence the model was trained on. The empty array agrees with the reference on those
//!   roles (`content or ""`). It is the one shape whose bytes the (unported) differential
//!   structurally cannot pin — see `text_content`.
//! - **It also refuses a list of things the reference RENDERS.** Each is a shape whose
//!   rendering is not worth guessing at, because the reference reaches it through Python's
//!   `str()`/`repr()` rather than through JSON — and, with array-of-parts now accepted, none
//!   of them is a shape a conforming OpenAI client emits. Enumerated because "it refuses
//!   more" is not a property anyone should have to rediscover:
//!
//!   | input | the reference renders | here |
//!   |---|---|---|
//!   | `content` a non-string, non-array scalar anywhere | `str()` of it | refused |
//!   | `content` falsy non-string, non-array (`0`, `false`) | `""`, via `content or ""` | refused |
//!   | `content` non-string on `latest_reminder` | `str()`/repr — no `or ""` guard at all | refused |
//!   | `content` a scalar or object on a `tool` turn | `str()`: `true`→`True`, `{}`→`{}` | refused |
//!   | a content block's `type` non-string | `[Unsupported {'a': 1}]`, Python's repr | refused |
//!   | `tools`/`tool_calls` falsy non-array (`{}`, `0`) | ignored | refused, but only on the role that parses the key |
//!   | a tool entry whose `function` is not an object | the scalar as a schema line | refused |
//!   | `function.name` non-string | `name="5"` | refused |
//!   | `function.name` null | `name="None"` — a call to a tool that does not exist | refused |
//!   | `task` invalid on a turn the assert never reaches | silently inert | refused |
//!   | `reasoning_content` falsy non-string (`0`, `[]`) | `""`, via `rc = … or ""` | refused |
//!   | `reasoning_content` truthy non-string | `str()`/repr of it, e.g. `<think>[1]</think>` | refused |
//!   | tool-call `id` / `tool_call_id` non-string | used as-is — they are live sort keys | refused |
//!   | `tools` on an `assistant`/`latest_reminder` turn | nothing, but drop_thinking flips | refused |
//!
//!   All measured against the reference 2026-08-06.
//! - **The rule that decides refuse-vs-reproduce, so the two are not per-case taste:**
//!   *Python's `None` is reproduced where it lands in CONTENT — text the model merely reads.
//!   It is refused where it lands in STRUCTURE, and everything that would go through
//!   `str()`/`repr()` is refused everywhere.*
//!
//!   Content, so reproduced: `<tool_result>None</tool_result>` (a null `tool` content),
//!   `<｜latest_reminder｜>None` (absent or null), `[Unsupported None]` (a block's absent or
//!   null `type`). `None` there is one determined four-character literal and the worst it
//!   does is put an odd word in the prompt — where refusing would 400 on the `tool` case,
//!   which is what an OpenAI client sends when a tool returns nothing.
//!
//!   Structure, so refused: a null `function.name` renders `name="None"` in the reference —
//!   a call to a tool that does not exist, which no client can dispatch. Reproducing it
//!   would hand the caller a broken tool call instead of an error. (An ABSENT `function.name`
//!   is a `KeyError` there and refused here too, so only the present-and-null case is a
//!   deliberate divergence.) Everything else is not determined anyway: `str(True)` is `True`
//!   and a dict interpolates as `{'a': 1}` with single quotes, so "reproduce the easy subset"
//!   would be a rule nobody could state.
//! - **`tools` on a `user` or `tool` turn is ACCEPTED and ignored**, matching the reference:
//!   `merge_tool_messages` rebuilds both dicts, so the key never reaches the `any(...)` scan.
//!   A round-1 version refused those too; review caught it as a disagreement in the *reject*
//!   direction, which is the one a strict port gets wrong most easily.
//!
//! ## The one behaviour that is NOT reproduced: Python's number formatting
//!
//! `python_json` matches `json.dumps`'s **separators** and its `ensure_ascii=False`, which is
//! what the tool-schema and `string="false"` bytes hinge on. It does not match Python's
//! **number repr**, and cannot without changing how the whole crate parses JSON. Measured
//! 2026-08-06, `json.dumps(json.loads(x))` against `serde_json`:
//!
//! | input | Python | this port | |
//! |---|---|---|---|
//! | `1e30`, `1e16` | `1e+30`, `1e+16` | `1e+30`, `1e+16` | agree |
//! | `1e-4`, `0.1`, `2.0` | `0.0001`, `0.1`, `2.0` | same | agree |
//! | `9007199254740993` | exact | exact | agree (`u64`, not `f64`) |
//! | `1e-5` | `1e-05` | `0.00001` | **differs** |
//! | `1e-7`, `2.5e-8` | `1e-07`, `2.5e-08` | `1e-7`, `2.5e-8` | **differs** |
//! | `1e-30` | `1e-30` | `9.999999999999999e-31` | **differs** (a parse ULP, not a format) |
//! | `123456789012345678901234567890` | exact digits | `1.2345678901234568e+29` | **differs** |
//!
//! So: Python switches to exponential below `1e-4` and zero-pads the exponent to two digits;
//! `ryu` does neither. Reachable from an ordinary JSON-Schema `minimum`/`multipleOf` of
//! `1e-5`, which would shift the bytes of the *system* prompt. The complete fix is
//! `serde_json/arbitrary_precision`, which preserves the literal — but that is a crate-wide
//! feature: it changes `Value::Number` for `format.rs`, `v4_config.rs` and GLM's own
//! `tools_system_turn`, none of which are this track's to move. Recorded rather than
//! half-fixed, because a formatter that closed three of the four rows would look repaired
//! and still be wrong. `tests::boundary`'s `numeric_rendering_diverges_from_python` pins the
//! table.
//!
//! > **PORT NOTE 2026-08-16.** `glimmer_encoding::py_float` is a *different* answer to
//! > a neighbouring question and is deliberately NOT reached for here. It reproduces Python's
//! > `repr(float)` for Glimmer's ATEM values, where this module needs `json.dumps` of a whole
//! > `Value` — and the two disagree about integers, which `json.dumps` writes as integers and
//! > `repr` would not see at all. Wiring `py_float` into `python_json`'s number path is the
//! > shape of the real fix and is strictly larger than it looks: it would change GLM's tool
//! > schemas too, so it needs GLM's gold ids re-run. Named here so the next reader finds the
//! > candidate rather than re-deriving that it exists.
//!
//! Same root cause, same decision: `json.loads` accepts `NaN`/`Infinity` and `serde_json`
//! does not. So `arguments` of `{"x": NaN}` is decoded per-key there and takes the
//! unparseable-fallback branch here; and `arguments` of a bare `NaN` parses there and then
//! raises `AttributeError` on `.items()`, where here it renders as one `arguments`
//! parameter. The divergence runs in both directions and neither is reachable from a client
//! that emits standard JSON.

pub mod message;
pub mod parse;
pub mod render;

#[cfg(test)]
mod tests;

pub use message::{
    AssistantTurn, Body, Instructions, Message, Tool, ToolCall, message_from_openai,
    messages_from_openai,
};
pub use parse::{ParsedMessage, ParsedToolCall, parse_message_from_completion_text};
pub use render::{EncodeOpts, encode_messages};

// ============================================================
// Special tokens
// ============================================================

/// Beginning of sequence. `tokenizer.json` id 0.
pub const BOS: &str = "<｜begin▁of▁sentence｜>";
/// End of an assistant turn. `generation_config.json`'s only `eos_token_id`, id 1.
pub const EOS: &str = "<｜end▁of▁sentence｜>";
const THINK_OPEN: &str = "<think>";
const THINK_CLOSE: &str = "</think>";
/// Not `<｜DSML｜>`: the token is the *bare* `｜DSML｜`, id 128825, and the surrounding
/// `<…>`/`</…>` are ordinary text. `<｜DSML｜invoke` is therefore three-ish tokens, not one.
const DSML: &str = "｜DSML｜";
const USER: &str = "<｜User｜>";
const ASSISTANT: &str = "<｜Assistant｜>";
const LATEST_REMINDER: &str = "<｜latest_reminder｜>";

// ============================================================
// Modes
// ============================================================

/// Whether the generation prompt leaves `<think>` open.
///
/// **Thinking is a PREFILL, not a flag the model reads** — the same lesson GLM's path
/// carries. `Thinking` ends the prompt at an open `<think>` and the model reasons until it
/// emits `</think>`; `Chat` closes it immediately (`<｜Assistant｜></think>`) and the model
/// answers straight away. There is no "no-think" token in this vocabulary and the reference
/// never emits one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThinkingMode {
    /// `<｜Assistant｜></think>` — the reasoning block is closed before it starts.
    Chat,
    /// `<｜Assistant｜><think>` — the generation prompt ends inside the reasoning block.
    Thinking,
}

/// How much deliberation to ask for. Realized **purely as a text prefix** at the very front
/// of the prompt, before the system message; nothing else in the encoding changes.
///
/// Ignored in [`ThinkingMode::Chat`], where there is no reasoning block to lengthen.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ReasoningEffort {
    /// The reference's default. Adds nothing at all.
    #[default]
    Low,
    High,
    Max,
}

impl ReasoningEffort {
    /// The prefix text, verbatim from `REASONING_EFFORT_PROMPTS`. Note the trailing blank
    /// line on the two non-empty ones: it is what separates the prefix from the system
    /// message, so it belongs to the prefix and not to the caller.
    const fn prompt(self) -> &'static str {
        match self {
            Self::Low => "",
            Self::High => concat!(
                "Reasoning Effort: Absolute maximum with no shortcuts permitted.\n",
                "You MUST be very thorough in your thinking and comprehensively decompose \
                 the problem to resolve the root cause, rigorously stress-testing your logic \
                 against all potential paths, edge cases, and adversarial scenarios.\n",
                "Explicitly write out your entire deliberation process, documenting every \
                 intermediate step, considered alternative, and rejected hypothesis to \
                 ensure absolutely no assumption is left unchecked.\n\n",
            ),
            Self::Max => concat!(
                "Reasoning Effort: Beyond maximum — exhaustive, relentless, and \
                 uncompromising.\n",
                "You MUST reason with the utmost depth and rigor, leaving absolutely nothing \
                 to chance: exhaustively decompose the problem into its most fundamental \
                 components, trace every causal chain to its root, and resolve the underlying \
                 cause rather than any surface symptom.\n",
                "Do not stop reasoning until you have independently verified the solution \
                 from multiple angles and are certain that no assumption remains unchecked \
                 and no error remains undiscovered.\n\n",
            ),
        }
    }
}

/// A quick-instruction token, appended to a message to ask for one auxiliary classification
/// or short-form generation instead of a normal reply.
///
/// `<｜extracted_url｜>` from the README is deliberately absent: it is not a task, it is
/// text the caller puts *inside* the user content (`{prompt}<｜extracted_url｜>{url}`) before
/// setting [`Task::ReadUrl`]. The reference's `DS_TASK_SP_TOKENS` has the same six entries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Task {
    /// Search-or-answer routing. The only task placed *after* the assistant prefix.
    Action,
    Query,
    Authority,
    Domain,
    /// On an ASSISTANT message: appended after that turn's EOS, so the next assistant
    /// message is the generated title.
    Title,
    ReadUrl,
}

impl Task {
    const fn token(self) -> &'static str {
        match self {
            Self::Action => "<｜action｜>",
            Self::Query => "<｜query｜>",
            Self::Authority => "<｜authority｜>",
            Self::Domain => "<｜domain｜>",
            Self::Title => "<｜title｜>",
            Self::ReadUrl => "<｜read_url｜>",
        }
    }
}
