//! Build script: panics are the correct failure mode for a broken toolchain.
#![allow(clippy::expect_used)]

//! Compile the HIP kernels with hipcc and link libamdhip64 — only under the `rocm`
//! feature, so `cargo check` / CPU-side dev needs no GPU toolchain. (The cold-expert
//! io_uring streamer is the `io-uring` crate now, talking to the syscalls directly —
//! no liburing system lib.)

use std::path::Path;
use std::process::Command;

fn main() {
    if std::env::var("CARGO_FEATURE_VULKAN").is_ok() {
        return vulkan(); // second backend: glslc instead of hipcc, no HIP at all.
    }
    if std::env::var("CARGO_FEATURE_ROCM").is_err() {
        return; // CPU-only build: no HIP toolchain required.
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let kernels = [
        "linalg", "moe", "mla", "attn", "fwd", "vmm", "indexer", "async",
    ];
    let hipcc = std::env::var("HIPCC").unwrap_or_else(|_| "hipcc".into());
    // ponytail: default gfx1151 (Strix Halo); override for other ROCm nodes (e.g.
    // gfx1010 on rh-desktop's RX 5700) with RIVOLI_OFFLOAD_ARCH.
    println!("cargo:rerun-if-env-changed=RIVOLI_OFFLOAD_ARCH");
    let arch = std::env::var("RIVOLI_OFFLOAD_ARCH").unwrap_or_else(|_| "gfx1151".into());
    let offload = format!("--offload-arch={arch}");

    // Headers are #included, not compiled units — track them so an edit forces a rebuild.
    println!("cargo:rerun-if-changed=kernels/common.hpp");
    let mut objs = Vec::new();
    for k in kernels {
        let src = format!("kernels/{k}.hip");
        let obj = format!("{out_dir}/{k}.o");
        println!("cargo:rerun-if-changed={src}");
        let mut cmd = Command::new(&hipcc);
        cmd.args([&offload, "-O3", "-fPIC"]);
        let status = cmd
            .args(["-c", &src, "-o", &obj])
            .status()
            .expect("run hipcc");
        assert!(status.success(), "hipcc failed on {src}");
        objs.push(obj);
    }

    let lib = format!("{out_dir}/librivolikernels.a");
    // `ar crs` only adds/replaces members — it never prunes ones dropped from the
    // list, so a since-deleted kernel's stale .o lingers and duplicate-symbol-clashes.
    // Start from a clean archive every build.
    let _ = std::fs::remove_file(&lib);
    let mut ar = Command::new("ar");
    ar.arg("crs").arg(&lib);
    for o in &objs {
        ar.arg(o);
    }
    assert!(ar.status().expect("run ar").success(), "ar failed");

    println!("cargo:rustc-link-search=native={out_dir}");
    println!("cargo:rustc-link-lib=static=rivolikernels");
    for dir in ["/usr/lib64", "/opt/rocm/lib", "/usr/lib"] {
        if Path::new(dir).join("libamdhip64.so").exists() {
            println!("cargo:rustc-link-search=native={dir}");
            break;
        }
    }
    println!("cargo:rustc-link-lib=dylib=amdhip64");
}

/// The `vulkan` arm: compile every `kernels/vk/*.comp` to SPIR-V in OUT_DIR, which
/// `src/vk.rs` picks up with `include_bytes!`. Nothing is linked — the loader is
/// opened at runtime by `ash`, so a Vulkan build needs no GPU library at link time.
/// Wave width and rows-per-workgroup, defined ONCE here and injected into both
/// languages: `-D` on the glslc command line, and a generated `dims.rs` the Rust side
/// includes. They used to be declared twice with a "must match" comment and nothing
/// checking, which is a regression against HIP — there `ROW_GRID`/`ROW_BLOCK` derive
/// from the single `common.hpp` define, so the launcher geometry and the shader cannot
/// disagree. If they did disagree here the launcher would dispatch too few workgroups
/// and the missing output rows would simply keep their previous contents: no fault, no
/// validation diagnostic, wrong numbers.
const VK_WAVE: u32 = 32;
const VK_ROWS_PER_BLOCK: u32 = 8;

fn vulkan() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let glslc = std::env::var("GLSLC").unwrap_or_else(|_| "glslc".into());
    std::fs::write(
        format!("{out_dir}/dims.rs"),
        format!(
            "// @generated by build.rs — the single source is VK_WAVE/VK_ROWS_PER_BLOCK there.\n\
             pub const WAVE: u32 = {VK_WAVE};\n\
             pub const ROWS_PER_BLOCK: u32 = {VK_ROWS_PER_BLOCK};\n"
        ),
    )
    .expect("write dims.rs");
    println!("cargo:rerun-if-env-changed=GLSLC");
    // The DIRECTORY entry catches an added/removed shader; the per-file entries below
    // catch edits. Both are needed — and `common.glsl` is #included, not compiled, so
    // without its own entry an edit to it silently ships stale SPIR-V (exactly the
    // common.hpp staleness bug this repo already hit once).
    println!("cargo:rerun-if-changed=kernels/vk");

    let mut shaders: Vec<_> = std::fs::read_dir("kernels/vk")
        .expect("read kernels/vk")
        .map(|e| e.expect("dir entry").path())
        .collect();
    shaders.sort(); // deterministic build order
    for path in &shaders {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    // EVERY shader is compiled and checked before anything fails, and the failures are
    // reported together.
    //
    // Aborting at the first bad shader reports a FLOOR, not a count — and the situation
    // where that bites is the common one: change a shared constant, break four shaders,
    // get told about one. Fix it, rebuild, get told about the next. Each rebuild teaches
    // one fact the compiler already knew in full. It also hides breakage during review:
    // a `#error` in an early-sorted shader masked a second one in a later shader, and
    // that only surfaced because a deliberate-break check reported "did not fire" when
    // it should have.
    let mut failures: Vec<String> = Vec::new();
    for src in shaders.iter().filter(|p| p.extension().is_some_and(|e| e == "comp")) {
        let stem = src.file_stem().expect("shader stem").to_string_lossy();
        let spv = format!("{out_dir}/{stem}.spv");
        let out = Command::new(&glslc)
            .args(["--target-env=vulkan1.3", "-O", "-Ikernels/vk"])
            .arg(format!("-DWAVE={VK_WAVE}"))
            .arg(format!("-DROWS_PER_BLOCK={VK_ROWS_PER_BLOCK}"))
            .arg(src)
            .args(["-o", &spv])
            .output()
            .expect("run glslc");
        if !out.status.success() {
            failures.push(format!(
                "{}: glslc failed\n{}",
                src.display(),
                String::from_utf8_lossy(&out.stderr).trim()
            ));
            // The later checks read the .spv, which does not exist or is stale. Skipping
            // them is not "stopping early": every OTHER shader is still checked.
            continue;
        }
        failures.extend(spirv_val(&spv));
        failures.extend(no_subgroup_arithmetic(&spv));
        failures.extend(no_reciprocal_rewrite(&spv));
    }
    assert!(
        failures.is_empty(),
        "\n\n{} shader problem(s) — ALL of them, not just the first:\n\n{}\n",
        failures.len(),
        failures.join("\n\n")
    );
}

/// Fail the build if a module declares the `GroupNonUniformArithmetic` capability —
/// i.e. someone reached for `subgroupAdd`/`subgroupMul`/`subgroupMin`... in a
/// reduction.
///
/// Greedy decode must be bit-reproducible, and those ops have an
/// IMPLEMENTATION-DEFINED summation order. Every reduction here is a fixed
/// `subgroupShuffleDown` halving ladder instead (kernels/vk/common.glsl::wave_sum,
/// matching common.hpp). That rule was a comment in docs/VULKAN.md; this makes it a
/// build error, because a comment does not survive sixteen kernel ports.
///
/// Skipped with a warning if `spirv-dis` is absent, like `spirv-val` above.
///
/// Returns findings rather than panicking, so the caller can report every shader's
/// problems at once.
fn no_subgroup_arithmetic(spv: &str) -> Vec<String> {
    let Some(text) = disassemble(spv) else { return Vec::new() };
    ["GroupNonUniformArithmetic", "GroupNonUniformClustered"]
        .iter()
        .filter(|banned| text.contains(*banned))
        .map(|banned| {
            format!(
                "{spv}: declares OpCapability {banned} — a subgroup reduce (subgroupAdd \
                 and friends) has an implementation-defined summation order and breaks \
                 greedy decode's reproducibility. Use the wave_sum shuffle ladder."
            )
        })
        .collect()
}

/// Fail the build if `-O` turned a division into a multiply by a reciprocal.
///
/// `glslc -O` rewrites `a / K` for a literal K into `a * fl(1/K)`. For K = 448 that
/// differs from a true IEEE divide by 1 ULP on 55% of inputs — measured, not feared —
/// and hipcc (`-O3`, no `-ffast-math`) keeps a real `fdiv`, so the two backends'
/// numbers silently diverged. That defeats the premise the whole port rests on, and
/// nothing else catches it: the numeric oracles' tolerances are orders of magnitude
/// looser than 1 ULP, and even the byte-exact comparisons are protected by an
/// unambiguity margin that is precisely wide enough to hide it.
///
/// The determinism story here already assumes the toolchain does not rewrite float
/// arithmetic — that is what the fixed shuffle ladder and the `subgroupAdd` ban are
/// for. This is proof it does, so the assumption becomes a check.
///
/// THE RULE: no `OpFMul` by a float constant whose mantissa is non-zero. Multiplying by
/// a power of two (0.125, 512.0, 2^-6) is exact and common in the e4m3/bf16 paths;
/// multiplying by anything else is either an optimizer-invented reciprocal or an
/// author-written scale that deserves an argument. Pass the divisor in at runtime — an
/// operand the optimizer cannot see is an operand it cannot fold.
fn no_reciprocal_rewrite(spv: &str) -> Vec<String> {
    // Legitimate non-power-of-two constant multiplies, if one is ever justified: add
    // the exact printed value here with a comment saying why it is safe. Empty on
    // purpose — every current kernel either divides at runtime or scales by 2^n.
    const ALLOWED: &[&str] = &[];

    let mut found = Vec::new();
    let Some(text) = disassemble(spv) else { return found };
    // name -> printed value, from `%float_x = OpConstant %float 0.125`
    let mut consts = std::collections::HashMap::new();
    for line in text.lines() {
        if let Some((name, val)) = line.split_once(" = OpConstant %float ") {
            consts.insert(name.trim(), val.trim());
        }
    }
    for line in text.lines() {
        if !line.contains(" = OpFMul ") {
            continue;
        }
        for tok in line.split_whitespace() {
            let Some(val) = consts.get(tok) else { continue };
            if ALLOWED.contains(val) {
                continue;
            }
            let Ok(v) = val.parse::<f32>() else { continue };
            // Exact power of two (or zero): mantissa bits all clear.
            if v == 0.0 || (v.to_bits() & 0x007f_ffff) == 0 {
                continue;
            }
            found.push(format!(
                "{spv}: multiplies by the non-power-of-two constant {val}\n  {}\n  \
                 This is how `glslc -O` spells `a / {:.0}` — and a reciprocal multiply \
                 is NOT bit-identical to the divide hipcc emits, so the two backends \
                 diverge silently. Pass the divisor in as a push constant (see \
                 append_kv.comp), or if this multiply is deliberate and safe, add \
                 \"{val}\" to ALLOWED in build.rs with the reason.",
                line.trim(),
                1.0 / v
            ));
        }
    }
    found
}

/// `spirv-dis` output, or `None` with a warning if the tool is absent — same optional
/// treatment as `spirv-val`, since it ships in a different package from glslc.
fn disassemble(spv: &str) -> Option<String> {
    match Command::new("spirv-dis").arg("--no-color").arg(spv).output() {
        Ok(o) if o.status.success() => Some(String::from_utf8_lossy(&o.stdout).into_owned()),
        Ok(_) => panic!("spirv-dis failed on {spv}"),
        Err(e) => {
            println!("cargo:warning=spirv-dis not run on {spv} ({e}); SPIR-V unchecked");
            None
        }
    }
}

/// Validate a compiled module with `spirv-val`.
///
/// This is STATIC module validation — it catches malformed SPIR-V, bad decorations,
/// and capability/extension mismatches. It does NOT see synchronisation, descriptor,
/// or buffer-device-address misuse; only the VK_LAYER_KHRONOS_validation runtime layer
/// does, and that layer is a separate install (see docs/VULKAN.md "Risks").
///
/// A missing `spirv-val` warns rather than fails: it ships in a different package from
/// glslc, and a box that can build shaders should not be blocked on the checker.
fn spirv_val(spv: &str) -> Vec<String> {
    match Command::new("spirv-val").arg(spv).output() {
        Ok(o) if o.status.success() => Vec::new(),
        Ok(o) => vec![format!(
            "{spv}: spirv-val rejected the module\n{}",
            String::from_utf8_lossy(&o.stderr).trim()
        )],
        Err(e) => {
            println!("cargo:warning=spirv-val not run on {spv} ({e}); SPIR-V unchecked");
            Vec::new()
        }
    }
}
