//! Kimi-K3's shapes, epsilons and startup refusals — the deviceless arithmetic every other
//! file in this arm reads and none re-derives.
//!
//! Ungated like `crate::v4::geometry` and for the same reason: this is the half where a wrong
//! answer is silent (a scale over the wrong head width, a cache row missing its rope slot, a
//! context past the attend kernel's staging bound), and CI compiles only the featureless
//! build. Every width here is DERIVED from the validated `K3TextConfig` — `k3_config.rs`
//! already proved the layer partition, the degenerate router groups and the flag set, so this
//! file adds only what the ENGINE needs on top: composed widths, the two epsilons that are
//! not the model-wide one, and the ceilings the kernels impose.

use anyhow::{Result, ensure};
use rivoli_artifact::k3_config::K3TextConfig;

/// The MLA LoRA-norm epsilon: `q_a_layernorm` and `kv_a_layernorm` take **1e-6**, not the
/// model-wide `rms_norm_eps` 1e-5.
///
/// Pinned by READING, because no measurement can settle it: the C reference passes 1e-5 here
/// and DIVERGES from first-party (`k3:docs/reference/k3-architecture.md` §5, G0 item 11);
/// first-party `KimiRMSNorm` defaults to 1e-6 with no eps argument at modeling M:368/383.
/// The anchor's tolerance table (`crates/oracles/tests/common/tolerance.rs::K3`) records why
/// numbers cannot decide it — the eps moves the MLA operator by 2.22e-5 against its own fp32
/// rounding floor of 1.70e-5, a margin of 1.3x, so `mla` is `ExactOnly` and the constant is
/// pinned here instead. The goldens were generated by the first-party stack, so 1e-6 is the
/// value they attest.
pub const MLA_LORA_EPS: f32 = 1e-6;

/// The KDA head norm's epsilon is the MODEL-WIDE `rms_norm_eps`, not [`MLA_LORA_EPS`].
///
/// Not a constant, because it is the config's number — this is the record of WHICH eps that
/// operator takes, next to the one that is not. Provenance: `k3:tests/k3_kernels.rs`'s
/// `gate_norm` fixtures read `rms_norm_eps` off the golden's own tiny config and the device
/// kernel matched the first-party `o_norm` captures under `kda_op`'s tolerance — so 1e-5 at
/// the head norm is anchored, where the LoRA norms' 1e-6 had to be read.
pub fn head_norm_eps(cfg: &K3TextConfig) -> f32 {
    cfg.rms_norm_eps as f32
}

/// The attend kernel's staging ceiling: `launch_mha_attend` stages one score row per KV
/// position in LDS and its guard 1004 refuses `kv > 8192` (`ATTEND_MAX_KV`,
/// `crates/backend/src/hip_attn.rs`). This arm attends the FULL allocated cache behind an
/// additive mask (see `engine.rs`), so `kv == max_ctx` on every call and the kernel's bound
/// becomes a `--ctx` ceiling, refused at the door rather than at the first MLA layer.
pub const ATTEND_MAX_KV: usize = 8192;

/// Rows of the fixed-point MoE accumulator — one per STREAM (residents on the compute
/// stream, misses on the miss stream), same value and same no-cross-stream-join reason as
/// `crate::v4::engine::MOE_ACC_ROWS`. Lives in geometry because [`Dims::from_config`] sizes
/// nothing from it but `engine.rs` and the widths gate both read it, and the deviceless
/// build has no `engine.rs`.
pub const MOE_ACC_ROWS: usize = 2;

/// Every composed width the loop reads, derived once and refused early.
///
/// A struct rather than call sites reading `cfg` directly, because the traps in this model
/// are ORDER and WIDTH traps (`k3:docs/reference/k3-architecture.md` §10): `hidden` 7168 vs
/// the 3584 latent, the 192 full head width vs the 128 nope half, the 12288 KDA channel
/// count that three different tensors share. Deriving each ONCE, beside the ensure that
/// makes it safe, is what keeps a call site from recomputing one wrongly.
#[derive(Debug, Clone, Copy)]
pub struct Dims {
    /// KDA channels: `num_heads * head_dim` = 12288 — the width of q/k/v/g projections, the
    /// conv, and `dt_bias`, all per (head, channel).
    pub kda_ch: usize,
    /// One MLA query head: `qk_nope + qk_rope` = 192. Also one cached KEY row per head —
    /// the 64 unrotated rope dims are CACHED AND SCORED (trap 9), so the cache row carries
    /// them and dropping the term is unrepresentable rather than forgotten.
    pub q_head: usize,
    /// One `kv_b` output head: `qk_nope + v_head` = 256, split `[k_nope | v]` at append.
    pub kv_b_head: usize,
    /// MLA softmax scale, `(qk_nope + qk_rope)^-0.5` — over the FULL 192-wide head, not
    /// `qk_nope^-0.5` (trap 8). Computed here so no launch site owns the exponent.
    pub mla_scale: f32,
    /// `kv_a_proj_with_mqa`'s output: `kv_lora + qk_rope` = 576 — the latent plus the shared
    /// rope slot, ONE projection. `kv_a_layernorm` covers the latent HALF only, never the
    /// rope slot (`k3:docs/reference/k3-architecture.md` §5).
    pub kv_a_out: usize,
    /// The fused shared MLP's intermediate: `n_shared * moe_inter` = 6144. The checkpoint
    /// ships ONE fused `[7168, 6144]` MLP, not two experts — reading this width off the
    /// latent passed a literal-width assertion once (`crates/oracles/tests/k3_anchor.rs`),
    /// which is why it is derived here from the two factors.
    pub shared_inter: usize,
    /// AttnRes snapshot count: `ceil(n_layers / attn_res_block_size)` = 8. The last block is
    /// 9 layers deep (84..=92) — 93 is not a multiple of 12, and the reference never
    /// validates divisibility, so neither does this (`k3:docs/reference/k3-architecture.md`
    /// §3).
    pub res_blocks: usize,
}

impl Dims {
    /// Derive the composed widths, refusing what the kernels would refuse later.
    ///
    /// The refusals here are the ones `K3TextConfig::validate` deliberately does not own:
    /// they are KERNEL ceilings (LDS staging, power-of-two head reductions, the attn-res
    /// source cap), not checkpoint structure, so they live with the engine that launches
    /// against them.
    pub fn from_config(cfg: &K3TextConfig) -> Result<Self> {
        let la = &cfg.linear_attn_config;
        // The recurrence and the gated head norm reduce per head in a power-of-two tree and
        // refuse `head_dim > 1024` or non-power-of-two (guards 1002/1003,
        // `crates/backend/src/hip_attn.rs`). Refused at the door so a mis-sized artifact
        // fails with the dimension named, not with an argument-guard code mid-prefill.
        ensure!(
            la.head_dim.is_power_of_two() && la.head_dim <= 1024,
            "KDA head_dim {} is not a power of two <= 1024 — the recurrence kernel's \
             per-head reduction tree has no other shape",
            la.head_dim
        );
        // `launch_short_conv_silu_f32` accepts taps in 2..=16 (guard 1002).
        ensure!(
            (2..=16).contains(&la.short_conv_kernel_size),
            "short_conv_kernel_size {} is outside the conv kernel's 2..=16",
            la.short_conv_kernel_size
        );
        let res_blocks = cfg.n_layers.div_ceil(cfg.attn_res_block_size);
        // `launch_attn_res` stages its per-source scores in registers and refuses
        // `nsrc > 16` (guard 1003, ATTN_RES_MAX_SRC). The deepest fold mixes every block
        // plus the prefix sum.
        ensure!(
            res_blocks < 16,
            "{res_blocks} attn-res blocks + the prefix sum exceed the fold kernel's 16-source \
             staging"
        );
        let q_head = cfg.qk_nope_head_dim + cfg.qk_rope_head_dim;
        Ok(Self {
            kda_ch: la.num_heads * la.head_dim,
            q_head,
            kv_b_head: cfg.qk_nope_head_dim + cfg.v_head_dim,
            // f64 through the sqrt so the f32 rounding happens once, at the end — the C
            // computes `1/sqrtf((float)qh)`; one rounding either way, and this direction is
            // the one that cannot underflow first.
            mla_scale: (1.0 / (q_head as f64).sqrt()) as f32,
            kv_a_out: cfg.kv_lora_rank + cfg.qk_rope_head_dim,
            shared_inter: cfg.n_shared * cfg.moe_inter,
            res_blocks,
        })
    }
}

/// Refuse a context this arm cannot decode, BEFORE the pin reads a terabyte.
///
/// Two bounds, each named. `max_ctx >= 2` because a run that spends its whole ceiling on the
/// prompt has no room to generate. [`ATTEND_MAX_KV`] because the MLA layers attend the full
/// allocated cache behind an additive mask — `kv == max_ctx` on every call — so the attend
/// kernel's LDS staging bound is a hard `--ctx` ceiling here, not a long-context tail case.
/// The KDA layers impose nothing: their state is `[heads][d][d]` regardless of context,
/// which is the reason `rivoli_core::legality` answers `--ctx` differently on this arm.
pub fn check_context(max_ctx: usize) -> Result<()> {
    ensure!(
        max_ctx >= 2,
        "--ctx {max_ctx} leaves no room for a prompt and a generated token"
    );
    ensure!(
        max_ctx <= ATTEND_MAX_KV,
        "--ctx {max_ctx} exceeds {ATTEND_MAX_KV}, the attend kernel's per-launch KV staging \
         bound (ATTEND_MAX_KV) — this arm scores the whole allocated cache behind a mask, so \
         the kernel ceiling is the context ceiling. Pass --ctx {ATTEND_MAX_KV} or below.",
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    // Panic-on-failure is the test idiom; `expect` is the whole allowance this module needs.
    #![allow(clippy::expect_used)]

    use super::*;
    use rivoli_artifact::k3_config::K3Config;
    use rivoli_artifact::schema::parse_config;

    /// The vendored real config — the same file `k3_config.rs`'s own tests pin — so every
    /// number below is the checkpoint's, not this file's.
    const REAL: &str = include_str!("../../../../docs/measurement/k3-reference/config.json");

    fn real() -> K3TextConfig {
        parse_config::<K3Config>(REAL)
            .expect("the vendored K3 config parses")
            .text
    }

    /// Every composed width at the real checkpoint's values, one assertion each, so a
    /// transposed factor fails naming the width and not seven layers downstream. The
    /// numbers are `k3:docs/reference/k3-architecture.md` §1's, restated as the expected
    /// side of a derivation rather than as prose.
    #[test]
    fn the_composed_widths_are_the_checkpoints() {
        let d = Dims::from_config(&real()).expect("the real config derives");
        assert_eq!(d.kda_ch, 12288, "96 heads x 128");
        assert_eq!(d.q_head, 192, "qk_nope 128 + qk_rope 64");
        assert_eq!(d.kv_b_head, 256, "qk_nope 128 + v_head 128");
        assert_eq!(d.kv_a_out, 576, "kv_lora 512 + qk_rope 64");
        assert_eq!(d.shared_inter, 6144, "2 shared x 3072, ONE fused MLP");
        assert_eq!(
            d.res_blocks, 8,
            "ceil(93 / 12); the last block is 9 layers deep"
        );
        // Trap 8 as a value: the scale is over the FULL 192 — compared BIT-exactly against
        // the same one-rounding derivation, so a second f32 rounding in `from_config` would
        // also fail here — and it must NOT equal the nope-width scale, asserted too because
        // at some widths the two could coincide and this test should refuse such a fixture.
        let over_192 = (1.0 / (192f64).sqrt()) as f32;
        assert_eq!(d.mla_scale.to_bits(), over_192.to_bits());
        assert!((f64::from(d.mla_scale) - 1.0 / (128f64).sqrt()).abs() > 1e-3);
    }

    /// The context door: both bounds refuse, the interior passes. The upper bound is the
    /// attend kernel's, so this also pins that [`ATTEND_MAX_KV`] here agrees with the
    /// guard's documented value — a drift would make the door admit a run the kernel then
    /// kills mid-prefill with a bare guard code.
    #[test]
    fn the_context_door_refuses_both_ends() {
        assert!(check_context(1).is_err(), "no room to generate");
        assert!(check_context(2).is_ok());
        assert!(check_context(ATTEND_MAX_KV).is_ok());
        let err = check_context(ATTEND_MAX_KV + 1).expect_err("past the staging bound");
        assert!(err.to_string().contains("ATTEND_MAX_KV"), "{err:#}");
    }

    /// [`MLA_LORA_EPS`] is first-party's 1e-6, not the C's 1e-5 — the divergence the
    /// tolerance table proves unmeasurable (`mla` is `ExactOnly` at 1.3x its floor), pinned
    /// as a value so widening it to the model eps is a red test and not a silent drift.
    #[test]
    fn the_lora_eps_is_first_partys() {
        assert_eq!(MLA_LORA_EPS, 1e-6);
        assert!((f64::from(head_norm_eps(&real())) - 1e-5).abs() < 1e-12);
    }
}
