//! **The head tail: the one absolute fixture, and the two defects with no silent half.**
//!
//! `hc_head` -> final `RMSNorm` -> `ParallelHead` is the last thing before a token, and the
//! place a self-relative gate is weakest: a transliteration error shared by the base path and
//! its own defect variants cancels on both sides. So this binary pins the tail ABSOLUTELY
//! against a torch capture at readable dimensions, pins its DTYPE boundary (the half no
//! numeric comparison can see), and gives `HeadHcNoRsqrt` / `HeadHcRsqrtPerCopy` the
//! every-case coverage a matrix row would otherwise have given them.
//!
//! Split out of `v4_oracle.rs` on 2026-08-15 for the 800-line ceiling; the family's
//! orientation stays in that file's header and the shared toy driver in
//! `common/oracle_probe.rs`.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use rivoli_oracles::golden::diff;
use rivoli_oracles::v4oracle::forward::{Capture, Defect, HeadRows, HeadTailW, Oracle};
use rivoli_oracles::v4oracle::weights::{V4Config, WMat};

#[path = "common/oracle_probe.rs"]
mod oracle_probe;
use oracle_probe::{all_bf16, cases, fingerprint, matching, model, run};

/// The head tail at toy dimensions, captured from CPU PyTorch on 2026-08-05.
///
/// **This is the ABSOLUTE gate on the head tail, and the reason it exists is the same reason
/// `bf16_reduction_matches_torch_and_not_a_running_fold` (sibling `v4_oracle_reduction.rs`)
/// exists.** Every other head-tail assertion in the family is SELF-RELATIVE -- a defected
/// capture against an undefected one --
/// so a transliteration error shared by `hc_head` and its own defect variants cancels on both
/// sides and passes silently. That is exactly how the indexer's running-fold survived. If
/// `hc_head`'s rsqrt were scoped wrong in both the base path and `HeadHcRsqrtPerCopy`, or the
/// final norm's eps landed outside the sqrt in both, the other 30 tests would still be green.
///
/// Generated by transliterating model.py:709-716 (`hc_head`), :197-202 (`RMSNorm`) and
/// :731-740 (`ParallelHead`, `full_logits=False`) straight into torch calls -- not by
/// restating the Rust. Dimensions are deliberately tiny (`hc_mult` 4, `dim` 8, `s` 2,
/// `vocab` 5) so the whole fixture is readable, and `s = 2` so `x[:, -1]` is a real choice.
///
/// Dtypes follow the checkpoint, and the test asserts that they do: `H`, `NORM_W` and
/// `LM_HEAD` are bf16-representable because the checkpoint stores them bf16, while `FN` is
/// full f32 because `hc_head_fn` is F32 on disk -- so the mixes dot exercises f32 mantissas
/// that a bf16 fixture would have hidden.
#[rustfmt::skip]
mod torch_head_tail {
    pub const HC_MULT: usize = 4;
    pub const DIM: usize = 8;
    pub const S: usize = 2;
    pub const VOCAB: usize = 5;
    pub const H: &[f32] = &[
        -0.05517578, -0.28710938, -0.14746094, -0.0078125, -1.796875, -0.2578125, 1.921875,
        -0.23632813, 2.21875, -0.25, 0.53125, 0.578125, 0.9375, 0.52734375, -0.2109375,
        0.51953125, -0.54296875, 1.390625, 0.08544922, -0.21777344, 0.31054688, 0.66796875,
        0.39648438, -0.33203125, -1.609375, -0.12011719, -0.06689453, -0.13671875, 0.6328125,
        -0.5390625, 1.390625, -0.96484375, -0.9375, 2.0, 0.10986328, -0.33984375, -0.796875,
        -0.74609375, -0.62109375, -1.4375, 1.9765625, -0.06738281, -1.625, -0.38867188,
        -0.546875, 0.10986328, 1.40625, -0.703125, 0.11816406, -0.37109375, -0.0021514893,
        0.59765625, 1.546875, 0.33789063, -0.5078125, 0.17285156, -0.15820313, -2.265625,
        1.4375, -0.13574219, 2.71875, 1.4609375, -1.328125, -0.11425781
    ];
    pub const FN: &[f32] = &[
        0.440603, -0.66241807, -0.24728929, -0.13473506, 0.6656537, 0.9849724, 0.039184332,
        0.093170285, -0.13936427, -0.40719315, 0.01683204, -0.8812992, -0.8122814, 0.3493402,
        -0.08314953, 0.021388406, 1.1909121, -1.0306041, -0.11617905, 0.19755034, -0.012285116,
        -0.4201789, -0.16754936, 0.050195172, 0.5776188, -0.03540141, 0.5788603, -0.065610915,
        0.031231571, 0.89210266, 1.1707971, 0.44770864, -0.20019218, -0.7726562, 0.5258006,
        0.56279606, -0.5170723, 0.27976602, 0.16123955, -0.3741502, 0.96389794, -0.21715029,
        -0.4851133, -0.112384826, 0.017547777, -0.15141359, -0.6811052, -0.36952764,
        0.18584248, 0.19504797, -0.93740416, -0.13653417, -0.3739525, -0.7811996, 0.65430826,
        0.04110952, 0.7716346, -0.4844922, -0.37774345, 0.156617, -0.35271907, -0.92980933,
        0.04721228, -0.39673546, -0.22678863, -0.006180152, 0.9809605, 0.3741006, -0.31392458,
        -0.70439285, 0.09982608, -0.14046784, -0.9091174, -0.21177873, -1.3339996, 0.27655193,
        0.3117143, -0.21688096, -0.31344137, -0.60645866, -0.38015386, -0.49603975,
        -0.12530302, -0.63456744, -0.047734298, -0.17878447, -0.35324326, -0.33005747,
        -0.4325743, -0.43922296, -0.2842426, 0.046071798, -0.9829653, -0.50217706, 0.75698155,
        0.17544046, 0.5727456, 0.29420432, 1.1298723, -0.33078817, 0.27781653, -0.36367008,
        0.824201, 0.16153276, -0.15936637, -0.9153573, -0.026848827, -1.0524422, 0.14650427,
        0.40450522, 0.51041394, 0.730945, 0.005767892, -0.6457507, 0.40119773, -0.0018267105,
        0.25621048, 0.17447938, -0.64957625, -0.077361606, 1.3280479, 0.0018734756,
        -0.17327635, 0.46909046, -1.0369962, 0.3421054, 0.30048266, 0.3960198
    ];
    pub const BASE: &[f32] = &[
        -1.8474996, -1.169862, -0.7948558, -0.084306315
    ];
    pub const SCALE: &[f32] = &[
        0.9867983
    ];
    pub const NORM_W: &[f32] = &[
        1.4375, -0.52734375, -1.484375, -0.10253906, -1.546875, 0.859375, -1.6484375,
        -0.5859375
    ];
    pub const LM_HEAD: &[f32] = &[
        -0.8125, 1.421875, 0.37695313, 0.54296875, -0.5234375, 1.3046875, -0.67578125,
        -1.0703125, -0.48242188, 0.38085938, -2.484375, 2.4375, -1.2109375, -1.3203125,
        -0.828125, -0.25195313, 0.3671875, -0.40820313, -1.8203125, -0.53125, -1.1171875,
        0.39257813, 0.55859375, 2.3125, 0.72265625, -0.031982422, -0.7109375, 0.109375,
        0.58203125, 0.40625, -0.6328125, 0.18164063, -1.1640625, 0.56640625, 0.953125,
        0.052001953, 0.1328125, -0.7890625, -0.953125, -0.65234375
    ];
    pub const HC_HEAD_OUT: &[f32] = &[
        1.75, -0.033935547, 0.45507813, 0.453125, 0.83984375, 0.515625, -0.092285156,
        0.36914063, 0.046875, -0.17871094, 0.07763672, -0.025878906, 0.28515625, 0.14257813,
        -0.11425781, -0.096191406
    ];
    pub const FINAL_NORM_OUT: &[f32] = &[
        3.328125, 0.02355957, -0.890625, -0.061279297, -1.7109375, 0.5859375, 0.20117188,
        -0.28515625, 0.46875, 0.65625, -0.8046875, 0.018432617, -3.078125, 0.85546875, 1.3125,
        0.39257813
    ];
    pub const LOGITS: &[f32] = &[
        1.6791062, 3.4799843, 6.7748985, -1.3114338, -3.5308638
    ];
}

#[test]
fn the_head_tail_matches_torch_absolutely() {
    use torch_head_tail as t;
    // The fixture must be adversarial in the way it claims: bf16 where the checkpoint stores
    // bf16, and NOT bf16 for `hc_head_fn`, which is F32 on disk. If `FN` were bf16-valued the
    // mixes dot would never exercise an f32 mantissa and this gate would be weaker than it
    // reads.
    assert!(
        all_bf16(t::H),
        "the residual stream must be bf16, as the reference stores it"
    );
    let weights_bf16 = all_bf16(t::NORM_W) && all_bf16(t::LM_HEAD);
    assert!(weights_bf16, "norm/head weights are bf16 on disk");
    assert!(
        !all_bf16(t::FN),
        "hc_head_fn is F32 on disk; a bf16 fixture would not exercise it"
    );

    let cfg = V4Config {
        dim: t::DIM,
        vocab_size: t::VOCAB,
        ..V4Config::toy()
    };
    assert_eq!(
        cfg.hc_mult,
        t::HC_MULT,
        "the fixture was captured at hc_mult 4"
    );
    let o = Oracle::new(cfg.clone(), Defect::None);
    let hw = HeadTailW {
        hc_head_fn: t::FN.to_vec(),
        hc_head_base: t::BASE.to_vec(),
        hc_head_scale: t::SCALE.to_vec(),
        norm: t::NORM_W.to_vec(),
        lm_head: WMat::Dense {
            rows: t::VOCAB,
            cols: t::DIM,
            v: t::LM_HEAD.to_vec(),
        },
    };
    let mut cap = Capture::default();
    o.head_tail(
        &hw,
        HeadRows {
            h: t::H,
            s: t::S,
            step_tag: "abs",
        },
        &mut cap,
    );

    // Bitwise, not `assert_close`. At these dimensions a sequential f32 dot reproduces
    // torch's reduction exactly -- checked when the fixture was captured, all 5 logits equal
    // -- so there is no re-association slack to hide behind, and the two bf16 tensors are
    // quantized coarsely enough that any real disagreement clears the format anyway.
    for (name, want) in [
        ("hc_head_out", t::HC_HEAD_OUT),
        ("final_norm_out", t::FINAL_NORM_OUT),
        ("logits", t::LOGITS),
    ] {
        let got = cap
            .float(&format!("head.abs.{name}"))
            .unwrap_or_else(|| panic!("{name} missing"));
        assert_eq!(got.len(), want.len(), "head.abs.{name} length");
        for (i, (g, w)) in got.iter().zip(want).enumerate() {
            assert_eq!(
                g.to_bits(),
                w.to_bits(),
                "head.abs.{name}[{i}]: oracle {g:e} != torch {w:e} -- the transliteration \
                 disagrees with the reference, and no self-relative test in this family can \
                 see it"
            );
        }
    }
}

#[test]
fn the_head_tail_stores_bf16_where_the_reference_does_and_f32_where_it_does_not() {
    // The dtype boundary is the whole of the head tail's precision contract, and it is a live
    // choice on the device: `hc_head` returns `y.to(dtype)` and `RMSNorm.forward` returns
    // `(...).to(dtype)` -- both bf16 -- while `ParallelHead.forward` is `F.linear(x.float(),
    // weight)` on an f32 parameter and is never stored back. Getting the last one wrong by
    // reusing a bf16-storing GEMV is silent: the argmax usually survives it.
    let (cfg, _) = model();
    let r = run(3, 12, Defect::None);
    // Prefill (12 rows in) and a decode step (1 row in), because the claim that `logits` is
    // ONE row is only a claim at all when more than one row went in.
    for (cap, phase) in [(&r.pre, "pre"), (&r.dec, "dec0")] {
        let get = |n: &str| {
            cap.float(&format!("head.{phase}.{n}"))
                .unwrap_or_else(|| panic!("head.{phase}.{n} is missing"))
                .to_vec()
        };
        let (hc, nm, lg) = (get("hc_head_out"), get("final_norm_out"), get("logits"));
        // The `[s, dim]` shapes are NOT re-asserted here: `Capture::push` already refuses a
        // tensor whose length disagrees with its declared shape, and `head_tail` declares
        // them from the same `cfg`. `logits` IS asserted, because it is the one shape a
        // correct-looking implementation gets wrong -- `ParallelHead.forward` slices
        // `x[:, -1]`, so 12 rows in must still give ONE row of logits out. An implementation
        // that returned all rows would push `[s, vocab]` and satisfy `push` perfectly.
        assert_eq!(
            lg.len(),
            cfg.vocab_size,
            "head.{phase}.logits is not a single row"
        );
        for (n, v) in [
            ("hc_head_out", &hc),
            ("final_norm_out", &nm),
            ("logits", &lg),
        ] {
            assert!(
                v.iter().all(|x| x.is_finite()),
                "head.{phase}.{n} has a non-finite value"
            );
            assert!(v.iter().any(|&x| x != 0.0), "head.{phase}.{n} is all zero");
        }
        assert!(
            all_bf16(&hc),
            "head.{phase}.hc_head_out is not bf16 -- `y.to(dtype)` was lost"
        );
        assert!(
            all_bf16(&nm),
            "head.{phase}.final_norm_out is not bf16 -- RMSNorm's store was lost"
        );
        // The other direction, and the load-bearing one. `all_bf16` on all three would pass
        // an implementation that rounded everything; this forbids it. Not a probabilistic
        // hope: each logit is an f32 dot product of `dim` bf16 terms, so landing on a bf16
        // grid point needs its low 16 mantissa bits to come out zero. If this fires, the
        // logits are being stored through bf16 somewhere -- the head is wrong, not unlucky.
        assert!(
            !all_bf16(&lg),
            "every one of head.{phase}.logits' {} values is bf16-representable -- the logits \
             were stored through bf16, which the reference never does",
            lg.len()
        );
    }
}

#[test]
fn the_head_mhc_rsqrt_is_load_bearing_in_every_case() {
    // `expect()` (sibling `v4_oracle.rs`) gives these two no matrix row: everything they can
    // reach, they reach, and the only thing upstream is the layer stack, which `head_tail`
    // cannot touch because it borrows `h` immutably. So what is assertable here is what a
    // matrix row would otherwise have given -- that each fires in EVERY case, and that they
    // are not one defect wearing two names.
    //
    // **The magnitudes are a NEGATIVE result and are recorded as one.** The prediction before
    // measuring was that both would clear one bf16 ulp, on the reasoning that dropping or
    // mis-scoping an rsqrt of ~1.7 moves the mHC gates by ~10%. Measured over the 16-case
    // grid, 2026-08-05, smallest relative movement of any head golden:
    //
    //   HeadHcNoRsqrt       4.899e-3  (median .hc_head_out 7.9e-2, max 2.1e-1)
    //   HeadHcRsqrtPerCopy  4.284e-4  (median .logits 3.6e-3, max 7.6e-3)
    //
    // The bf16 ulp at 1.0 is 2^-7 = 7.8125e-3, so **the prediction failed for BOTH** -- their
    // worst cases sit 1.6x and 18x BELOW one ulp of the tensor's own scale. (`Diff.rel`
    // normalises by `max |b|`, so the ulp at the tensor's max is the right comparison.) An
    // earlier revision of this comment put the ulp at 2^-8 and concluded that `HeadHcNoRsqrt`
    // cleared it; that was wrong -- bf16 keeps 7 explicit mantissa bits, not 8.
    //
    // Both are still caught here, because this binary compares BIT-EXACTLY at TOY dimensions.
    //
    // **Do not carry that to the device.** An earlier revision of this comment concluded
    // "the device-side head gate must be bitwise, not `assert_close`". That is WRONG at real
    // dimensions, and `the_reassociation_floor_bounds_any_tolerance_these_goldens_can_have`
    // (sibling `v4_oracle_reduction.rs`) measures why: at dim 4096 a CORRECT wave-reduced
    // kernel already differs from this oracle on ~0.08% of bf16 elements, so a bitwise gate
    // would reject correct code -- and `HeadHcRsqrtPerCopy`'s signal is the same ORDER as that
    // noise, the two swapping places between fixtures. The mHC denominator's scope has to be
    // settled by reading the kernel, or at small dimensions against
    // `the_head_tail_matches_torch_absolutely`, and not by comparing full-width activations
    // at all.
    //
    // The bound below is a fixture-regression pin at roughly a third of the measured worst
    // case, NOT a claim that any gate resolves either defect under tolerance.
    //
    // Why it is small is itself the reason not to widen it away: the toy draws the residual
    // copies i.i.d., so their per-copy RMS agree to ~5%, and the per-copy rsqrt is then nearly
    // the joint one. Whether the trained model's `hc_post` spreads them further is not
    // something this fixture can answer.
    let mut prints = Vec::new();
    for d in [Defect::HeadHcNoRsqrt, Defect::HeadHcRsqrtPerCopy] {
        let mut worst = f32::INFINITY;
        let mut fps = Vec::new();
        for c in cases() {
            let base = run(c.layer, c.prompt, Defect::None);
            let got = run(c.layer, c.prompt, d);
            let ds = diff(base.of(c.phase), got.of(c.phase));
            for suffix in [".hc_head_out", ".final_norm_out", ".logits"] {
                let hits = matching(&ds, suffix);
                assert!(
                    !hits.is_empty(),
                    "{d:?} at {c:?}: no *{suffix} golden exists"
                );
                assert!(
                    hits.iter().all(|h| h.changed > 0),
                    "{d:?} at {c:?}: left a *{suffix} golden bit-identical"
                );
                worst = hits.iter().fold(worst, |m, h| m.min(h.rel));
            }
            // The layer stack is untouched. Trivially true today -- `head_tail` takes
            // `&[f32]` -- and kept as a tripwire for the day someone gives it `&mut`.
            for h in matching(&ds, ".attn_out")
                .iter()
                .chain(matching(&ds, ".out").iter())
            {
                assert_eq!(
                    h.changed, 0,
                    "{d:?} at {c:?}: reached {} in the layer",
                    h.name
                );
            }
            fps.push(fingerprint(got.of(c.phase)));
        }
        println!("{d:?}: smallest relative movement over the grid = {worst:.3e}");
        assert!(
            worst > 1.4e-4,
            "{d:?}'s smallest movement fell to {worst:.3e}, below the 1.4e-4 pin (a third of \
             the 4.284e-4 measured on 2026-08-05). The fixture has become less able to \
             separate this defect, not more -- re-measure before moving the pin"
        );
        prints.push((d, fps));
    }
    assert_ne!(
        prints[0].1, prints[1].1,
        "the two head-rsqrt defects compute the same thing"
    );
}
