//! The Vulkan compute backend — the `rocm`-free twin of `hip.rs`. Instance/device
//! bring-up, memory, queue/timeline sync, and the `launch_*` surface over the SPIR-V
//! kernels in `kernels/vk/`. See docs/VULKAN.md.
//!
//! Everything hangs off one process-global [`Gpu`]. HIP hides its context inside the
//! runtime, which is why `hip.rs`'s launchers and `device.rs`'s buffers take nothing
//! but pointers; keeping ours global buys the same signatures, so `gpu.rs` and
//! `pin.rs` never learn a backend exists.

#![cfg(feature = "vulkan")]

use anyhow::{Result, anyhow, bail, ensure};
use ash::vk;
use futures_util::task::AtomicWaker;
use std::ffi::CStr;
use std::future::Future;
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Condvar, Mutex, OnceLock};
use std::task::{Context, Poll};
use tracing::{error, info, warn};

const VALIDATION_LAYER: &CStr = c"VK_LAYER_KHRONOS_validation";

/// Alignment an `O_DIRECT` read requires of its destination buffer. The cold-expert
/// streamer DMAs straight into a [`Buf`]'s host mapping, so a mapping that is not this
/// aligned makes every read fail `EINVAL` — deep inside the reaper, on some future
/// machine, long after startup. See [`Buf::host_mut`].
pub const O_DIRECT_ALIGN: usize = 4096;

/// Shaders read packed `u8`/`u16` weights as 32-bit WORDS — `VK_KHR_8bit_storage` is
/// deliberately not required (docs/VULKAN.md) — so the word holding the LAST byte of an
/// unaligned buffer extends up to 3 bytes past it. Every allocation is rounded up to
/// this so that read stays in bounds.
///
/// Found by GPU-assisted validation, not by an oracle: `embed_i8_row` over a
/// 5 x 37 = 185-byte table had invocation 36 read the word at offset 184, three bytes
/// past the end. Every numeric test PASSED — in the default config and under
/// synchronisation validation — because the out-of-range bytes land in the discarded
/// lanes of the word. GPU-AV was the only thing that could see it.
pub const WORD: usize = 4;

// `WAVE` and `ROWS_PER_BLOCK`, generated by build.rs from the same constants it
// passes to glslc with -D. Declaring them here as well and hoping the two stay equal
// is what HIP avoids by deriving ROW_GRID/ROW_BLOCK from one common.hpp define: a
// mismatch dispatches too few workgroups and the unwritten output rows keep their old
// contents — no fault, and no validation diagnostic either.
//
// WAVE is 32 because gfx1151 is native wave32; the pipelines pin it with
// `requiredSubgroupSize` + REQUIRE_FULL_SUBGROUPS, so a driver that cannot honour it
// fails at init rather than silently reducing gl_NumSubgroups (which would leave the
// upper rows of every workgroup unwritten — see gemv_f32.comp).
include!(concat!(env!("OUT_DIR"), "/dims.rs"));

/// Threads per workgroup. The shaders' `local_size_x`.
pub const BLOCK: u32 = ROWS_PER_BLOCK * WAVE;

/// Instance, device, the dedicated compute queue, and a command pool on it. Built
/// once by [`gpu`]; never dropped (see the note there).
pub struct Gpu {
    pub device: ash::Device,
    pub memprops: vk::PhysicalDeviceMemoryProperties,
    instance: ash::Instance,
    phys: vk::PhysicalDevice,
    /// Owns the dlopen'd libvulkan; must outlive the instance, never called through.
    _entry: ash::Entry,
    cmd: Mutex<Cmd>,
    pipes: Pipes,
    validation: bool,
    budget: bool,
    timeline: Timeline,
    /// Did the waiter thread actually start? `gpu()` publishes the context BEFORE
    /// spawning, so a spawn failure (EAGAIN under thread pressure) returns Err from
    /// the first call while every later call short-circuits on the published value and
    /// returns Ok. Without this flag the process would then run with no waiter: every
    /// `signal()` would submit happily and no Signal would ever resolve, presenting as
    /// a hang in the async path long after the transient failure that caused it.
    waiter: AtomicBool,
}

/// Count of validation ERROR/WARNING messages seen. Tests assert it is zero, so a
/// layer diagnostic FAILS THE RUN instead of scrolling past in a log nobody reads.
pub static VALIDATION_ERRORS: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(0);

unsafe extern "system" fn debug_callback(
    sev: vk::DebugUtilsMessageSeverityFlagsEXT,
    ty: vk::DebugUtilsMessageTypeFlagsEXT,
    data: *const vk::DebugUtilsMessengerCallbackDataEXT<'_>,
    _user: *mut std::ffi::c_void,
) -> vk::Bool32 {
    // SAFETY: the loader guarantees `data` points at a valid struct for this call.
    let msg = unsafe { (*data).message_as_c_str() }
        .unwrap_or(c"<no message>")
        .to_string_lossy()
        .into_owned();
    let err = sev.contains(vk::DebugUtilsMessageSeverityFlagsEXT::ERROR);
    // SAFETY: the loader guarantees `data` points at a valid struct for this call.
    let id = unsafe { (*data).message_id_name_as_c_str() }
        .unwrap_or(c"")
        .to_string_lossy()
        .into_owned();
    // Two classes are logged but NOT counted, because counting them would make the
    // assertion fire on something that is not a finding — and an assertion that cries
    // wolf gets deleted rather than triaged.
    //
    //   PERFORMANCE — advice, not misuse ("your dispatch is small").
    //   The layer talking ABOUT ITSELF — enabling GPU-AV makes it emit
    //   VALIDATION-SETTINGS ("GPU-AV and core both on is slow") and
    //   WARNING-Setting-Limit-Adjusted ("forcing vulkanMemoryModel to TRUE so I can
    //   instrument your shaders"). Those describe the checker's configuration, not our
    //   Vulkan usage, and without this the suite can NEVER pass under GPU-AV — which
    //   is the one checker that covers the bare-device-address design.
    //
    // Matched by exact message-ID name, not a substring of the body: narrow enough
    // that a real finding cannot hide behind it.
    let self_report = matches!(
        id.as_str(),
        "VALIDATION-SETTINGS" | "WARNING-Setting-Limit-Adjusted"
    );
    if !ty.contains(vk::DebugUtilsMessageTypeFlagsEXT::PERFORMANCE) && !self_report {
        VALIDATION_ERRORS.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }
    // stderr UNCONDITIONALLY, in addition to `tracing`.
    //
    // Not belt-and-braces: `tracing` alone is a NULL SINK in the binary that matters.
    // The test harness installs no subscriber, so the counter above would move while
    // the message text vanished — a validation failure would report as a bare number
    // with no way to learn what the layer said, and the counter moving would make the
    // messenger look like it worked. The alternative fix (install a subscriber in the
    // test binary) leaves the same hole for anything else that links this crate
    // without one. eprintln has no such dependency.
    let level = if err { "ERROR" } else { "WARNING" };
    eprintln!("vk validation {level}: {msg}");
    if err {
        tracing::error!("vk validation: {msg}");
    } else {
        warn!("vk validation: {msg}");
    }
    vk::FALSE
}

/// The one open command buffer every `launch_*` appends to, plus the fence
/// [`device_sync`] joins on. Mirrors HIP's default stream: launches queue up, the
/// sync submits and waits. One buffer, reset and refilled — no per-launch submit
/// (colibri measured submit cost as the thing that matters on RADV).
struct Cmd {
    /// The queue lives HERE, not on `Gpu`, and that placement is load-bearing.
    ///
    /// `vkQueueSubmit` requires the VkQueue to be externally synchronised. When the
    /// handle sat beside the mutex instead of inside it, "always submit under the
    /// guard" was a convention — and `Gpu::signal` broke it within a day of the rule
    /// being written down, while carrying a SAFETY comment citing the very invariant it
    /// violated. Inside the guard, submitting without the lock is a borrow error rather
    /// than something a reader has to notice.
    queue: vk::Queue,
    pool: vk::CommandPool,
    buf: vk::CommandBuffer,
    fence: vk::Fence,
    recording: bool,
    /// Set by any failure in [`Gpu::sync`]. Each of its fallible calls leaves the
    /// buffer in a DIFFERENT illegal state — invalid after a failed `end`, executable
    /// after a failed submit, *pending* after a failed fence wait — and the pool has
    /// no `RESET_COMMAND_BUFFER` bit, so `vkBeginCommandBuffer` is only legal from the
    /// initial state. Since `device_sync` returns a `Result` the engine can observe
    /// the error and carry on, which would put every later submit into undefined
    /// behaviour, silently, with no validation layer to say so. So the failure is
    /// STICKY: once poisoned, nothing is recorded or submitted again.
    poisoned: bool,
}

/// A compiled compute kernel. Every pipeline here has an EMPTY descriptor-set layout:
/// buffers reach the shader as device addresses in push constants, which is HIP's raw
/// pointer args translated literally (docs/VULKAN.md, "kernel raw pointer args").
struct Pipe {
    layout: vk::PipelineLayout,
    pipe: vk::Pipeline,
    /// Bytes the layout declares. `dispatch` asserts the push struct matches: pushing
    /// more than the range is a VUID violation with nothing else to catch it.
    push_size: u32,
}

/// Every kernel, compiled once at init. Grows one field per ported kernel.
struct Pipes {
    gemv_f32: Pipe,
    embed_i8_row: Pipe,
    append_kv: Pipe,
    gather_rope: Pipe,
    vadd: Pipe,
    argmax_reduce: Pipe,
}

// SAFETY: needed because ash models the DISPATCHABLE handles (`vk::Queue`,
// `vk::CommandBuffer`) as raw pointers, hence `!Send`/`!Sync`; the non-dispatchable
// ones are `u64` and already fine.
//
// The invariant is ENFORCED, not asserted. Everything Vulkan requires to be externally
// synchronised — the queue, the command pool, the command buffer — is a field of the
// private `Cmd` struct behind `self.cmd`, so reaching any of them requires the mutex
// guard and there is no discipline to remember. `device` is public, but `VkDevice` is
// internally synchronised.
//
// This comment used to describe a convention instead, and `Gpu::signal` violated it
// while citing it. If a future change moves a synchronised handle back out of `Cmd`,
// this paragraph becomes false again — keep them inside.
unsafe impl Send for Gpu {}
unsafe impl Sync for Gpu {}

static GPU: OnceLock<Gpu> = OnceLock::new();

/// The process-global context, built on first use.
///
/// Not dropped: it lives until exit, and tearing a Vulkan device down while the
/// engine's buffers (also static-lifetime, also never freed on the HIP side) still
/// hold handles would be strictly worse than letting the OS reclaim it.
pub fn gpu() -> Result<&'static Gpu> {
    // Double-checked: the fast path is a plain atomic load, and the slow path is
    // taken once per process. `OnceLock::get_or_init` alone would be wrong here —
    // `Gpu::new` is fallible, so init has to happen outside the closure, and two
    // threads racing would each build a whole VkInstance + VkDevice + pipeline set
    // with the loser's LEAKED (Gpu has no Drop, deliberately). The decode loop is
    // single-threaded so this never fires in the engine, but cargo's test harness
    // runs tests in parallel threads and every one of them calls `gpu()`.
    //
    // No deadlock surface: nothing reachable from `Gpu::new` calls `gpu()`.
    if let Some(g) = GPU.get() {
        return Ok(g);
    }
    static INIT: Mutex<()> = Mutex::new(());
    let _lk = INIT.lock().map_err(|_| anyhow!("vk init lock poisoned"))?;
    if let Some(g) = GPU.get() {
        return Ok(g);
    }
    let g = Gpu::new()?;
    let g = GPU.get_or_init(|| g);
    // Spawned here, not in `Gpu::new`: the waiter needs a `&'static Gpu`, which only
    // exists once the OnceLock owns it. Runs for the life of the process; `Gpu` is
    // never dropped, so there is nothing for it to outlive.
    std::thread::Builder::new()
        .name("rivoli-vk-timeline".into())
        .spawn(move || timeline_waiter(g))?;
    g.waiter.store(true, Ordering::Release);
    Ok(g)
}

impl Gpu {
    fn new() -> Result<Self> {
        // SAFETY: loads libvulkan; the returned Entry owns it for the process.
        let entry = unsafe { ash::Entry::load() }
            .map_err(|e| anyhow::anyhow!("no Vulkan loader: {e}"))?;

        let app = vk::ApplicationInfo::default()
            .application_name(c"rivoli")
            .api_version(vk::API_VERSION_1_3);
        let validation = Self::validation_layer(&entry);
        let all = [VALIDATION_LAYER.as_ptr()];
        // VK_EXT_debug_utils is what carries the layer's diagnostics to us. Without a
        // messenger, "validation ENABLED" would mean the layer talks to a settings
        // file and nothing else — reaching neither `tracing` nor a test assertion,
        // which is the same "green run mistaken for a validated one" the layer is
        // supposed to prevent. The extension is provided by the loader independently
        // of the layer, so we ask for it whenever it is advertised.
        let debug = Self::has_extension(&entry, ash::ext::debug_utils::NAME);
        let exts = [ash::ext::debug_utils::NAME.as_ptr()];
        let ci = vk::InstanceCreateInfo::default()
            .application_info(&app)
            .enabled_layer_names(&all[..validation as usize])
            .enabled_extension_names(&exts[..debug as usize]);
        // SAFETY: `ci` and everything it borrows outlive the call.
        let instance = unsafe { entry.create_instance(&ci, None) }?;
        if debug {
            Self::attach_messenger(&entry, &instance)?;
        }

        let (phys, qfam) = Self::pick(&instance)?;
        // NOTE: the queue handle is deliberately NOT fetched here. It belongs to `Cmd`,
        // behind the mutex, so that submitting without the guard cannot compile.
        // Live free-memory reporting; see `mem_info`. Optional because the fallback
        // (free == total) is merely useless, not wrong.
        let budget = Self::has_device_extension(&instance, phys, ash::ext::memory_budget::NAME);
        let device = Self::create_device(&instance, phys, qfam, budget)?;
        // SAFETY: `phys` is a live physical device from this instance.
        let memprops = unsafe { instance.get_physical_device_memory_properties(phys) };
        let cmd = Cmd::new(&device, qfam)?;
        let pipes = Pipes::new(&device)?;
        let timeline = Timeline::new(&device)?;

        Ok(Self {
            device,
            memprops,
            instance,
            phys,
            _entry: entry,
            cmd: Mutex::new(cmd),
            pipes,
            validation,
            budget,
            timeline,
            waiter: AtomicBool::new(false),
        })
    }

    /// Is `VK_LAYER_KHRONOS_validation` installed? Says so either way, at WARN when
    /// it is not — same rule as `device.rs`'s sole-tenant guard: a silently-inert
    /// safety net is worse than none, because you believe you are protected.
    ///
    /// This backend passes every buffer as a raw device address with no descriptor
    /// sets, and a bad address or a missing barrier reads plausible GARBAGE rather
    /// than faulting. The validation layer is the only thing that catches that class;
    /// `spirv-val` (run by build.rs) checks module wellformedness, not API use.
    fn validation_layer(entry: &ash::Entry) -> bool {
        // SAFETY: the loader is live.
        let Ok(layers) = (unsafe { entry.enumerate_instance_layer_properties() }) else {
            warn!("VULKAN VALIDATION OFF: could not enumerate instance layers");
            return false;
        };
        let found = layers.iter().any(|l| {
            l.layer_name_as_c_str()
                .is_ok_and(|n| n == VALIDATION_LAYER)
        });
        if found {
            info!("Vulkan validation layer ENABLED");
        } else {
            warn!(
                "VULKAN VALIDATION OFF: {} not installed. Buffer-device-address and \
                 synchronisation misuse will read garbage instead of failing.",
                VALIDATION_LAYER.to_string_lossy()
            );
        }
        found
    }

    fn has_extension(entry: &ash::Entry, name: &CStr) -> bool {
        // SAFETY: the loader is live.
        unsafe { entry.enumerate_instance_extension_properties(None) }
            .is_ok_and(|xs| xs.iter().any(|x| x.extension_name_as_c_str() == Ok(name)))
    }

    /// Route the validation layer's ERROR/WARNING messages into `tracing` and count
    /// them, so a diagnostic can FAIL A TEST rather than scroll past. Without this the
    /// layer's output goes wherever its settings file says, which is nowhere useful.
    fn attach_messenger(entry: &ash::Entry, instance: &ash::Instance) -> Result<()> {
        use vk::DebugUtilsMessageSeverityFlagsEXT as Sev;
        use vk::DebugUtilsMessageTypeFlagsEXT as Ty;
        let ci = vk::DebugUtilsMessengerCreateInfoEXT::default()
            .message_severity(Sev::ERROR | Sev::WARNING)
            .message_type(Ty::GENERAL | Ty::VALIDATION | Ty::PERFORMANCE)
            .pfn_user_callback(Some(debug_callback));
        let dbg = ash::ext::debug_utils::Instance::new(entry, instance);
        // SAFETY: `instance` is live and `ci` outlives the call. The messenger is
        // never destroyed — it must outlive every other object, and the instance is
        // itself never destroyed (see `gpu`).
        unsafe { dbg.create_debug_utils_messenger(&ci, None) }?;
        Ok(())
    }

    /// Whether this context is running under the validation layer. Tests print it so
    /// a green run is never mistaken for a validated one.
    pub fn validation(&self) -> bool {
        self.validation
    }

    /// First physical device whose queue families and features satisfy the whole
    /// contract. If none does, report EVERY missing item for the *last* candidate
    /// rather than a bare "no suitable device" — on a one-GPU box that is the answer.
    fn pick(instance: &ash::Instance) -> Result<(vk::PhysicalDevice, u32)> {
        // SAFETY: `instance` is live.
        let devices = unsafe { instance.enumerate_physical_devices() }?;
        let mut last: Option<(String, Vec<String>)> = None;
        for phys in devices {
            // SAFETY: `phys` came from this instance.
            let props = unsafe { instance.get_physical_device_properties(phys) };
            let name = props.device_name_as_c_str().map_or_else(
                |_| "<unnamed>".to_string(),
                |s| s.to_string_lossy().into_owned(),
            );
            let mut missing = Vec::new();
            if props.api_version < vk::API_VERSION_1_3 {
                missing.push(format!(
                    "Vulkan 1.3 (device reports {}.{})",
                    vk::api_version_major(props.api_version),
                    vk::api_version_minor(props.api_version)
                ));
            }
            let qfam = Self::compute_queue(instance, phys);
            if qfam.is_none() {
                missing.push("a COMPUTE queue family".into());
            }
            missing.extend(Self::missing_features(instance, phys));
            match (qfam, missing.is_empty()) {
                (Some(q), true) => return Ok((phys, q)),
                _ => last = Some((name, missing)),
            }
        }
        match last {
            Some((name, missing)) => bail!(
                "no Vulkan device meets the rivoli contract; closest was {name}, missing: {}",
                missing.join(", ")
            ),
            None => bail!("no Vulkan physical devices found"),
        }
    }

    /// A DEDICATED compute family (COMPUTE without GRAPHICS) if the device has one,
    /// else any COMPUTE family. Colibri measured the dedicated queue as the better
    /// choice on RADV (commit 4d4cacc) — it does not contend with the compositor.
    fn compute_queue(instance: &ash::Instance, phys: vk::PhysicalDevice) -> Option<u32> {
        // SAFETY: `phys` came from `instance`.
        let fams = unsafe { instance.get_physical_device_queue_family_properties(phys) };
        let compute =
            |f: &vk::QueueFamilyProperties| f.queue_flags.contains(vk::QueueFlags::COMPUTE);
        fams.iter()
            .position(|f| compute(f) && !f.queue_flags.contains(vk::QueueFlags::GRAPHICS))
            .or_else(|| fams.iter().position(compute))
            .map(|i| i as u32)
    }

    /// Every required feature the device lacks, named as the spec names it so the
    /// failure is actionable. Fail fast beats a mystery `VK_ERROR_DEVICE_LOST` later.
    fn missing_features(instance: &ash::Instance, phys: vk::PhysicalDevice) -> Vec<String> {
        let mut v11 = vk::PhysicalDeviceVulkan11Features::default();
        let mut v12 = vk::PhysicalDeviceVulkan12Features::default();
        let mut v13 = vk::PhysicalDeviceVulkan13Features::default();
        // Scoped so the pNext chain's mutable borrows end and the filled-in structs
        // can be read below.
        let core = {
            let mut f2 = vk::PhysicalDeviceFeatures2::default()
                .push_next(&mut v11)
                .push_next(&mut v12)
                .push_next(&mut v13);
            // SAFETY: `phys` is live; the chain is valid for the duration of the call.
            unsafe { instance.get_physical_device_features2(phys, &mut f2) };
            f2.features
        };

        let mut sub = vk::PhysicalDeviceSubgroupProperties::default();
        let mut size = vk::PhysicalDeviceSubgroupSizeControlProperties::default();
        let p2 = {
            let mut p2 = vk::PhysicalDeviceProperties2::default()
                .push_next(&mut sub)
                .push_next(&mut size);
            // SAFETY: as above.
            unsafe { instance.get_physical_device_properties2(phys, &mut p2) };
            vk::PhysicalDeviceProperties2 {
                properties: p2.properties,
                ..Default::default()
            }
        };

        let mut missing = Vec::new();
        let mut need = |ok: bool, what: &str| {
            if !ok {
                missing.push(what.to_string());
            }
        };
        // Lets ExpertDesc's six raw pointers stay six uint64 addresses in a push
        // constant instead of six descriptor bindings rewritten per expert.
        need(v12.buffer_device_address == vk::TRUE, "bufferDeviceAddress");
        // ...which the shader dereferences as uint64_t buffer references.
        need(core.shader_int64 == vk::TRUE, "shaderInt64");
        need(v12.timeline_semaphore == vk::TRUE, "timelineSemaphore");
        // The fp16 VQ codebook.
        need(v12.shader_float16 == vk::TRUE, "shaderFloat16");
        need(v11.storage_buffer16_bit_access == vk::TRUE, "storageBuffer16BitAccess");
        // WAVE 32 is not negotiable — the reductions are a fixed 32-lane ladder.
        need(v13.subgroup_size_control == vk::TRUE, "subgroupSizeControl");
        need(v13.compute_full_subgroups == vk::TRUE, "computeFullSubgroups");
        need(
            size.min_subgroup_size <= WAVE && WAVE <= size.max_subgroup_size,
            &format!(
                "a subgroup size of {WAVE} (device allows {}..={})",
                size.min_subgroup_size, size.max_subgroup_size
            ),
        );
        need(
            size.required_subgroup_size_stages.contains(vk::ShaderStageFlags::COMPUTE),
            "requiredSubgroupSizeStages including COMPUTE",
        );
        need(
            sub.supported_stages.contains(vk::ShaderStageFlags::COMPUTE),
            "subgroup operations in COMPUTE",
        );
        // The shaders declare local_size_x = BLOCK. Vulkan only GUARANTEES 128
        // invocations and (128,128,64), both below the 256 we need, so a conformant
        // minimum-limits device would fail vkCreateComputePipelines with an opaque
        // ERROR_INITIALIZATION_FAILED instead of naming the limit. gfx1151 allows
        // 1024; the point of this function is the machines that are not gfx1151.
        let lim = p2.properties.limits;
        need(
            lim.max_compute_work_group_invocations >= BLOCK,
            &format!(
                "maxComputeWorkGroupInvocations >= {BLOCK} (device allows {})",
                lim.max_compute_work_group_invocations
            ),
        );
        need(
            lim.max_compute_work_group_size[0] >= BLOCK,
            &format!(
                "maxComputeWorkGroupSize[0] >= {BLOCK} (device allows {})",
                lim.max_compute_work_group_size[0]
            ),
        );
        // VUID-VkPipelineShaderStageCreateInfo-pNext-02759: local_size_x must fit in
        // maxComputeWorkgroupSubgroups * requiredSubgroupSize.
        need(
            size.max_compute_workgroup_subgroups >= ROWS_PER_BLOCK,
            &format!(
                "maxComputeWorkgroupSubgroups >= {ROWS_PER_BLOCK} (device allows {})",
                size.max_compute_workgroup_subgroups
            ),
        );
        for (flag, name) in [
            (vk::SubgroupFeatureFlags::BASIC, "subgroup BASIC"),
            (vk::SubgroupFeatureFlags::SHUFFLE_RELATIVE, "subgroup SHUFFLE_RELATIVE"),
        ] {
            need(sub.supported_operations.contains(flag), name);
        }
        // On Strix Halo host RAM *is* GPU memory (GTT); the pin path writes resident
        // weights straight into device-local memory, so this heap must exist.
        // SAFETY: `phys` is live.
        let mp = unsafe { instance.get_physical_device_memory_properties(phys) };
        let want = vk::MemoryPropertyFlags::DEVICE_LOCAL | vk::MemoryPropertyFlags::HOST_VISIBLE;
        need(
            mp.memory_types[..mp.memory_type_count as usize]
                .iter()
                .any(|t| t.property_flags.contains(want)),
            "a DEVICE_LOCAL | HOST_VISIBLE memory type",
        );
        missing
    }

    fn has_device_extension(
        instance: &ash::Instance,
        phys: vk::PhysicalDevice,
        name: &CStr,
    ) -> bool {
        // SAFETY: `phys` came from `instance`.
        unsafe { instance.enumerate_device_extension_properties(phys) }
            .is_ok_and(|xs| xs.iter().any(|x| x.extension_name_as_c_str() == Ok(name)))
    }

    fn create_device(
        instance: &ash::Instance,
        phys: vk::PhysicalDevice,
        qfam: u32,
        budget: bool,
    ) -> Result<ash::Device> {
        let prio = [1.0f32];
        let qci = [vk::DeviceQueueCreateInfo::default()
            .queue_family_index(qfam)
            .queue_priorities(&prio)];
        let mut v11 = vk::PhysicalDeviceVulkan11Features::default().storage_buffer16_bit_access(true);
        let mut v12 = vk::PhysicalDeviceVulkan12Features::default()
            .buffer_device_address(true)
            .timeline_semaphore(true)
            .shader_float16(true);
        let mut v13 = vk::PhysicalDeviceVulkan13Features::default()
            .subgroup_size_control(true)
            .compute_full_subgroups(true);
        let core = vk::PhysicalDeviceFeatures::default().shader_int64(true);
        // Every REQUIRED extension is core in 1.3 — including subgroup_size_control
        // and buffer_device_address. memory_budget is the one optional extra.
        let exts = [ash::ext::memory_budget::NAME.as_ptr()];
        let ci = vk::DeviceCreateInfo::default()
            .queue_create_infos(&qci)
            .enabled_extension_names(&exts[..budget as usize])
            .enabled_features(&core)
            .push_next(&mut v11)
            .push_next(&mut v12)
            .push_next(&mut v13);
        // SAFETY: `phys` is live and `ci` outlives the call; features were verified
        // present by `missing_features` before we got here.
        Ok(unsafe { instance.create_device(phys, &ci, None) }?)
    }

    /// Free device memory and total, in bytes — `hipMemGetInfo`'s twin.
    ///
    /// `free` is LIVE, via VK_EXT_memory_budget: `DeviceTier::new` gates the tier on
    /// `capacity + 4 GiB headroom <= free`, and substituting the heap SIZE there would
    /// admit a tier that cannot actually fit alongside the compositor and the driver's
    /// own allocations. The failure would then surface as an OOM part-way through
    /// weight loading instead of a clean refusal at startup, which is precisely what
    /// the headroom rule and the sole-tenant guard exist to prevent.
    ///
    /// Falls back to `free == total` only if the extension is absent — and says so,
    /// because a budget guard silently comparing against the heap size is a guard that
    /// always passes.
    pub fn mem_info(&self) -> (usize, usize) {
        let heaps = &self.memprops.memory_heaps[..self.memprops.memory_heap_count as usize];
        let local: Vec<usize> = (0..self.memprops.memory_heap_count as usize)
            .filter(|&i| heaps[i].flags.contains(vk::MemoryHeapFlags::DEVICE_LOCAL))
            .collect();
        let total: u64 = local.iter().map(|&i| heaps[i].size).sum();
        if !self.budget {
            warn!("VK_EXT_memory_budget absent: reporting free = total ({total} B)");
            return (total as usize, total as usize);
        }
        let mut b = vk::PhysicalDeviceMemoryBudgetPropertiesEXT::default();
        let mut p2 = vk::PhysicalDeviceMemoryProperties2::default().push_next(&mut b);
        // SAFETY: `self.phys` is live; the chain outlives the call.
        unsafe {
            self.instance
                .get_physical_device_memory_properties2(self.phys, &mut p2)
        };
        let free: u64 = local
            .iter()
            .map(|&i| b.heap_budget[i].saturating_sub(b.heap_usage[i]))
            .sum();
        (free as usize, total as usize)
    }

    /// Device name, for startup logging and for test output.
    pub fn name(&self) -> String {
        // SAFETY: `self.phys` is live.
        let props = unsafe { self.instance.get_physical_device_properties(self.phys) };
        props.device_name_as_c_str().map_or_else(
            |_| "<unnamed>".to_string(),
            |s| s.to_string_lossy().into_owned(),
        )
    }
}

// ---------------------------------------------------------------------------
// Command recording — HIP default-stream semantics over one command buffer.
// ---------------------------------------------------------------------------

impl Cmd {
    fn new(device: &ash::Device, qfam: u32) -> Result<Self> {
        let pci = vk::CommandPoolCreateInfo::default().queue_family_index(qfam);
        // SAFETY: `device` is live; `pci` outlives the call.
        let pool = unsafe { device.create_command_pool(&pci, None) }?;
        let ai = vk::CommandBufferAllocateInfo::default()
            .command_pool(pool)
            .level(vk::CommandBufferLevel::PRIMARY)
            .command_buffer_count(1);
        // SAFETY: as above; exactly one buffer is requested, so index 0 exists.
        let buf = unsafe { device.allocate_command_buffers(&ai) }?[0];
        // SAFETY: as above.
        let fence = unsafe { device.create_fence(&vk::FenceCreateInfo::default(), None) }?;
        // SAFETY: `qfam` came from the queue-create-info; index 0 exists.
        let queue = unsafe { device.get_device_queue(qfam, 0) };
        Ok(Self {
            queue,
            pool,
            buf,
            fence,
            recording: false,
            poisoned: false,
        })
    }
}

impl Gpu {
    /// Append work to the open command buffer, opening one if needed, then serialise
    /// it against whatever comes next. The barrier is what makes a `launch_*` sequence
    /// behave like HIP's default stream — each kernel sees the previous one's writes.
    /// `f` MUST NOT own, or transitively own, a [`Buf`]. It runs with the `cmd` mutex
    /// held, and `Buf::drop` calls `Gpu::sync`, which takes that same non-reentrant
    /// mutex — so a closure that drops a `Buf` deadlocks with no compile-time signal.
    /// No current caller does (they capture `Copy` handles and borrowed slices), and
    /// nothing enforces it, so the rule lives here where the next launcher is written.
    fn enqueue(&self, f: impl FnOnce(&ash::Device, vk::CommandBuffer)) -> Result<()> {
        let mut cmd = self.cmd.lock().map_err(|_| anyhow!("vk command lock poisoned"))?;
        ensure!(
            !cmd.poisoned,
            "vk command buffer poisoned by an earlier device_sync failure"
        );
        if !cmd.recording {
            let bi = vk::CommandBufferBeginInfo::default()
                .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT);
            // SAFETY: the buffer is not pending — the previous submit was fence-waited
            // and the pool reset in `sync`.
            unsafe { self.device.begin_command_buffer(cmd.buf, &bi) }?;
            cmd.recording = true;
        }
        f(&self.device, cmd.buf);
        // COMPUTE **and** TRANSFER on both sides. Dispatches are not the only thing
        // recorded here — `memcpy_dtod` records a `vkCmdCopyBuffer`, so all four
        // orderings occur: dispatch→dispatch, dispatch→copy (compaction reading a slot
        // a kernel just wrote), copy→dispatch, copy→copy. Scoping only COMPUTE would
        // leave the two involving a copy unordered.
        //
        // NOT verified by a checker, unlike everything else load-bearing here. See
        // docs/VULKAN.md "Synchronisation validation does not cover compute→transfer":
        // the layer reports transfer↔transfer hazards but stays silent on this class
        // even with NO barrier at all, so a clean run says nothing either way. This is
        // spec-derived, and it is the weakest evidence in the backend.
        let bar = [vk::MemoryBarrier::default()
            .src_access_mask(vk::AccessFlags::SHADER_WRITE | vk::AccessFlags::TRANSFER_WRITE)
            .dst_access_mask(
                vk::AccessFlags::SHADER_READ
                    | vk::AccessFlags::SHADER_WRITE
                    | vk::AccessFlags::TRANSFER_READ
                    | vk::AccessFlags::TRANSFER_WRITE,
            )];
        let stages =
            vk::PipelineStageFlags::COMPUTE_SHADER | vk::PipelineStageFlags::TRANSFER;
        // SAFETY: recording is open on `cmd.buf`.
        unsafe {
            self.device.cmd_pipeline_barrier(
                cmd.buf,
                stages,
                stages,
                vk::DependencyFlags::empty(),
                &bar,
                &[],
                &[],
            );
        }
        Ok(())
    }

    /// Bind, push the constants, dispatch. `push` must be the `#[repr(C)]` mirror of
    /// the shader's `push_constant` block — the ONE place the two sides can disagree,
    /// so each launcher declares its struct next to the launch that uses it.
    fn dispatch<T>(&self, p: &Pipe, push: &T, groups_x: u32) -> Result<()> {
        // The push struct and the pipeline layout are declared in different places and
        // nothing else compares them. `T` must also have NO PADDING — reading padding
        // bytes as `u8` is UB, and a `u64` after an `i32` silently introduces four.
        ensure!(
            size_of::<T>() as u32 == p.push_size,
            "push constant {} B but the pipeline layout declares {} B",
            size_of::<T>(),
            p.push_size
        );
        // SAFETY: `T` is a `#[repr(C)]` struct of scalars with no padding (asserted
        // field-by-field where each push struct is declared), so every byte is
        // initialised and reading it as its own bytes is sound.
        let bytes =
            unsafe { std::slice::from_raw_parts((push as *const T).cast::<u8>(), size_of::<T>()) };
        self.enqueue(|d, cb| {
            // SAFETY: recording is open on `cb`; `p` was built against this device and
            // its layout declares exactly `size_of::<T>()` push-constant bytes.
            unsafe {
                d.cmd_bind_pipeline(cb, vk::PipelineBindPoint::COMPUTE, p.pipe);
                d.cmd_push_constants(cb, p.layout, vk::ShaderStageFlags::COMPUTE, 0, bytes);
                d.cmd_dispatch(cb, groups_x, 1, 1);
            }
        })
    }

    /// Submit whatever is recorded and block until it retires — one join per token,
    /// same contract as `hip::device_sync`. A no-op when nothing was launched.
    pub fn sync(&self) -> Result<()> {
        let mut cmd = self.cmd.lock().map_err(|_| anyhow!("vk command lock poisoned"))?;
        ensure!(
            !cmd.poisoned,
            "vk command buffer poisoned by an earlier device_sync failure"
        );
        if !cmd.recording {
            return Ok(());
        }
        // Poison FIRST, clear only on the success path: every early return below
        // leaves the buffer in a state `vkBeginCommandBuffer` may not be called from,
        // and there are four of them. Opting out of the analysis is cheaper and safer
        // than getting it right per-error-code.
        cmd.poisoned = true;
        // Make the kernels' writes available to the HOST domain, so a readback after
        // the fence is defined without a per-buffer invalidate. Host WRITES need no
        // matching barrier — vkQueueSubmit implies one for anything written before it.
        // TRANSFER as well as COMPUTE on the source side. `memcpy_dtod` records a
        // vkCmdCopyBuffer, so bytes reaching the host may have been written by the
        // copy rather than by a shader — as in `memcpy_dtod_after_dispatch_is_ordered`,
        // which reads back exactly such bytes. `Gpu::enqueue` was widened for this and
        // this barrier was not, which made the two internally inconsistent: either the
        // host barrier is load-bearing and had a hole, or it is redundant and
        // enqueue's premise is wrong. It is the former.
        let bar = [vk::MemoryBarrier::default()
            .src_access_mask(vk::AccessFlags::SHADER_WRITE | vk::AccessFlags::TRANSFER_WRITE)
            .dst_access_mask(vk::AccessFlags::HOST_READ)];
        let bufs = [cmd.buf];
        let si = [vk::SubmitInfo::default().command_buffers(&bufs)];
        // SAFETY: recording is open; the fence is unsignalled (reset below on every
        // path that signals it); nothing else touches this queue (see the Sync impl).
        unsafe {
            self.device.cmd_pipeline_barrier(
                cmd.buf,
                vk::PipelineStageFlags::COMPUTE_SHADER | vk::PipelineStageFlags::TRANSFER,
                vk::PipelineStageFlags::HOST,
                vk::DependencyFlags::empty(),
                &bar,
                &[],
                &[],
            );
            self.device.end_command_buffer(cmd.buf)?;
            cmd.recording = false;
            self.device.queue_submit(cmd.queue, &si, cmd.fence)?;
            self.device.wait_for_fences(&[cmd.fence], true, u64::MAX)?;
            self.device.reset_fences(&[cmd.fence])?;
            self.device
                .reset_command_pool(cmd.pool, vk::CommandPoolResetFlags::empty())?;
        }
        cmd.poisoned = false; // every step succeeded; the buffer is initial again
        Ok(())
    }
}

/// Block until all launched kernels retire — one join per token. `hip::device_sync`'s
/// twin, and the same contract: device pointers handed to a `launch_*` must stay valid
/// until this returns.
pub fn device_sync() -> Result<()> {
    gpu()?.sync()
}

// ---------------------------------------------------------------------------
// Pipelines
// ---------------------------------------------------------------------------

/// `Pipe::new(device, include_bytes!(<name>.spv), size_of::<PushTy>())`, so adding a
/// kernel is one line rather than five and the .spv name cannot drift from the field.
macro_rules! pipes {
    ($device:expr, $($field:ident : $push:ty),+ $(,)?) => {
        Pipes {
            $($field: Pipe::new(
                $device,
                include_bytes!(concat!(env!("OUT_DIR"), "/", stringify!($field), ".spv")),
                size_of::<$push>() as u32,
            )?),+
        }
    };
}

impl Pipes {
    fn new(device: &ash::Device) -> Result<Self> {
        Ok(pipes!(
            device,
            gemv_f32: GemvF32Push,
            embed_i8_row: EmbedI8Push,
            append_kv: AppendKvPush,
            gather_rope: GatherRopePush,
            vadd: VaddPush,
            argmax_reduce: ArgmaxPush,
        ))
    }
}

impl Pipe {
    fn new(device: &ash::Device, spv: &[u8], push_size: u32) -> Result<Self> {
        let words = ash::util::read_spv(&mut std::io::Cursor::new(spv))?;
        let smci = vk::ShaderModuleCreateInfo::default().code(&words);
        // SAFETY: `device` is live; `words` outlives the call.
        let module = unsafe { device.create_shader_module(&smci, None) }?;
        let ranges = [vk::PushConstantRange::default()
            .stage_flags(vk::ShaderStageFlags::COMPUTE)
            .offset(0)
            .size(push_size)];
        let plci = vk::PipelineLayoutCreateInfo::default().push_constant_ranges(&ranges);
        // SAFETY: as above. No descriptor-set layouts: every buffer is a device address.
        let layout = unsafe { device.create_pipeline_layout(&plci, None) }?;
        // Pin the subgroup to WAVE and require FULL subgroups, so the shaders' fixed
        // 32-lane shuffle ladder is a driver-enforced fact rather than an assumption.
        let mut req = vk::PipelineShaderStageRequiredSubgroupSizeCreateInfo::default()
            .required_subgroup_size(WAVE);
        let stage = vk::PipelineShaderStageCreateInfo::default()
            .stage(vk::ShaderStageFlags::COMPUTE)
            .module(module)
            .name(c"main")
            .flags(vk::PipelineShaderStageCreateFlags::REQUIRE_FULL_SUBGROUPS)
            .push_next(&mut req);
        let ci = [vk::ComputePipelineCreateInfo::default()
            .stage(stage)
            .layout(layout)];
        // SAFETY: as above.
        let pipes = unsafe { device.create_compute_pipelines(vk::PipelineCache::null(), &ci, None) }
            .map_err(|(_, e)| e)?;
        // SAFETY: the module is only needed while the pipeline is being created.
        unsafe { device.destroy_shader_module(module, None) };
        let pipe = *pipes.first().ok_or_else(|| anyhow!("no compute pipeline created"))?;
        Ok(Self {
            layout,
            pipe,
            push_size,
        })
    }
}

// ---------------------------------------------------------------------------
// Buffers
// ---------------------------------------------------------------------------

/// One device allocation: a `VkBuffer` bound to its own `VkDeviceMemory`, permanently
/// host-mapped, exposed to the kernels by its DEVICE ADDRESS.
///
/// This is the primitive `device.rs`'s `DeviceBuf`/`DeviceTier`/`VmmBuf` are built
/// from. On Strix Halo host RAM *is* GPU memory, so the same allocation is both
/// device-local (full bandwidth) and host-writable in place — the Vulkan spelling of
/// what `kernels/vmm.hip` does with HIP VMM.
pub struct Buf {
    buf: vk::Buffer,
    mem: vk::DeviceMemory,
    addr: u64,
    host: *mut u8,
    len: usize,
}

/// Every live [`Buf`], so a device address can be mapped back to the `VkBuffer` that
/// owns it.
///
/// This is the lookup table docs/VULKAN.md rejects for the launcher path — and the
/// reasoning still holds there. It is acceptable HERE because `vkCmdCopyBuffer` takes
/// handles and offsets and there is no copy-by-address command, and because the only
/// caller is arena compaction: occasional, already synchronous, already moving whole
/// expert blocks. A scan of a handful of entries next to a multi-megabyte copy is not
/// a cost. Do not let it grow a second caller on the decode path.
static ALLOCS: Mutex<Vec<Alloc>> = Mutex::new(Vec::new());

struct Alloc {
    base: u64,
    len: u64,
    buf: vk::Buffer,
}

/// The `VkBuffer` owning `[addr, addr+len)`, and the offset into it.
fn resolve(addr: u64, len: usize) -> Result<(vk::Buffer, u64)> {
    let allocs = ALLOCS.lock().map_err(|_| anyhow!("vk alloc registry poisoned"))?;
    let end = addr
        .checked_add(len as u64)
        .ok_or_else(|| anyhow!("device address {addr:#x} + {len} overflows"))?;
    allocs
        .iter()
        .find(|a| addr >= a.base && end <= a.base + a.len)
        .map(|a| (a.buf, addr - a.base))
        .ok_or_else(|| {
            anyhow!("device address {addr:#x}..{end:#x} is not inside any live Buf")
        })
}

impl Buf {
    pub fn new(len: usize) -> Result<Self> {
        ensure!(len > 0, "Buf::new(0): Vulkan rejects a zero-sized buffer");
        let g = gpu()?;
        // Allocate word-rounded (see [`WORD`]) but keep `self.len` at the REQUESTED
        // size. That asymmetry is the whole safety property and it is easy to "tidy"
        // away: storing `alloc` instead would silently widen `write_at`/`read_into`'s
        // bounds checks by up to three bytes, converting a fix for an accidental
        // overrun into a licence for deliberate ones. The padding exists so a shader's
        // 32-bit read of the FINAL byte stays inside the buffer — nothing else may see
        // it, and no caller may write into it.
        //
        // Free: Vulkan's memory requirements are granular far above 4 bytes, so this
        // rounds into padding the allocator was going to add anyway.
        let alloc = len.next_multiple_of(WORD);
        let bci = vk::BufferCreateInfo::default()
            .size(alloc as u64)
            .usage(
                vk::BufferUsageFlags::STORAGE_BUFFER
                    | vk::BufferUsageFlags::SHADER_DEVICE_ADDRESS
                    | vk::BufferUsageFlags::TRANSFER_SRC
                    | vk::BufferUsageFlags::TRANSFER_DST,
            )
            .sharing_mode(vk::SharingMode::EXCLUSIVE);
        // SAFETY: the device is live; `bci` outlives the call.
        let buf = unsafe { g.device.create_buffer(&bci, None) }?;
        // Allocation failure is RECOVERABLE here — the engine hits it during weight
        // residency and reports it — so every `?` below must undo what came before.
        // Leaking a VkBuffer per attempt would exhaust handles across a retry while
        // still reporting OOM, which reads as the wrong bug.
        match Self::finish(g, buf, len) {
            Ok(b) => Ok(b),
            Err(e) => {
                // SAFETY: `buf` is live, unbound, and referenced by nothing.
                unsafe { g.device.destroy_buffer(buf, None) };
                Err(e)
            }
        }
    }

    fn finish(g: &'static Gpu, buf: vk::Buffer, len: usize) -> Result<Self> {
        // SAFETY: `buf` was just created on this device.
        let req = unsafe { g.device.get_buffer_memory_requirements(buf) };
        let want = vk::MemoryPropertyFlags::DEVICE_LOCAL
            | vk::MemoryPropertyFlags::HOST_VISIBLE
            | vk::MemoryPropertyFlags::HOST_COHERENT;
        let types = &g.memprops.memory_types[..g.memprops.memory_type_count as usize];
        let idx = types
            .iter()
            .enumerate()
            .position(|(i, t)| {
                req.memory_type_bits & (1 << i) != 0 && t.property_flags.contains(want)
            })
            .ok_or_else(|| {
                // HOST_COHERENT is not a convenience here. Without it, host writes are
                // not visible to the device until vkFlushMappedMemoryRanges, and the
                // failure mode is STALE DATA READ AS VALID — no fault, no validation
                // message, wrong numbers. Refusing to allocate is the only safe
                // response short of implementing the flush, and a driver that forces
                // that choice should say so at startup rather than at token 300.
                anyhow!(
                    "no DEVICE_LOCAL|HOST_VISIBLE|HOST_COHERENT memory type for a {len} B \
                     buffer. Without HOST_COHERENT every in-place host fill needs an \
                     explicit vkFlushMappedMemoryRanges, which this backend does not do."
                )
            })? as u32;
        let mut flags =
            vk::MemoryAllocateFlagsInfo::default().flags(vk::MemoryAllocateFlags::DEVICE_ADDRESS);
        let ai = vk::MemoryAllocateInfo::default()
            .allocation_size(req.size)
            .memory_type_index(idx)
            .push_next(&mut flags);
        // SAFETY: as above.
        let mem = unsafe { g.device.allocate_memory(&ai, None) }?;
        let bind_and_map = || -> Result<*mut u8> {
            // SAFETY: `mem` was allocated for `buf`'s requirements, nothing is bound
            // yet, and the mapping covers the whole allocation.
            unsafe {
                g.device.bind_buffer_memory(buf, mem, 0)?;
                Ok(g.device
                    .map_memory(mem, 0, req.size, vk::MemoryMapFlags::empty())?
                    as *mut u8)
            }
        };
        let host = match bind_and_map() {
            Ok(h) => h,
            Err(e) => {
                // SAFETY: `mem` is live and (on the bind-failure path) unbound; the
                // caller destroys `buf`.
                unsafe { g.device.free_memory(mem, None) };
                return Err(e);
            }
        };
        let info = vk::BufferDeviceAddressInfo::default().buffer(buf);
        // SAFETY: `buf` was created with SHADER_DEVICE_ADDRESS and is bound.
        let addr = unsafe { g.device.get_buffer_device_address(&info) };
        // Registering is the LAST fallible step, and it comes after `mem` is allocated
        // and mapped — so its error path has to undo those, not just let `Buf::new`
        // destroy the buffer. Every other `?` in this function has a matching undo and
        // this one did not, which contradicted the comment two screens up saying they
        // all do.
        match ALLOCS.lock() {
            Ok(mut allocs) => allocs.push(Alloc {
                base: addr,
                len: len as u64,
                buf,
            }),
            Err(_) => {
                // SAFETY: `mem` is bound and mapped, owned solely by this half-built
                // Buf; the caller destroys `buf`.
                unsafe {
                    g.device.unmap_memory(mem);
                    g.device.free_memory(mem, None);
                }
                bail!("vk alloc registry poisoned");
            }
        }
        Ok(Self {
            buf,
            mem,
            addr,
            host,
            len,
        })
    }

    /// The buffer's DEVICE address, shaped as a pointer so the `launch_*` signatures
    /// match `hip.rs`'s exactly.
    ///
    /// **Not dereferenceable on the host.** Under HIP unified addressing the host and
    /// device see one address; under Vulkan they do not. Host access goes through
    /// [`Buf::write_at`] / [`Buf::read_into`], and the engine only ever passes these
    /// values through to kernels — which is why the swap costs `gpu.rs` nothing.
    pub fn ptr(&self) -> *const u8 {
        self.addr as *const u8
    }
    pub fn ptr_mut(&mut self) -> *mut u8 {
        self.addr as *mut u8
    }

    /// The HOST base of the permanent mapping — a real, dereferenceable pointer, and
    /// the target an io_uring O_DIRECT read DMAs into.
    ///
    /// This is the OTHER half of the pair [`ptr`](Self::ptr) documents: under HIP these
    /// are one number and `VmmBuf::ptr_mut` serves both purposes, which is why
    /// `pin.rs`'s `ArenaPool` can use one base for descriptor arithmetic and for
    /// `ReadSpec.dst`. Here they are unrelated, so the caller has to say which one it
    /// means. See docs/VULKAN.md, "Host pointer != device address".
    pub fn host_mut(&mut self) -> *mut u8 {
        self.host
    }

    /// Host-write `bytes` at byte offset `off`. HOST_COHERENT, and `vkQueueSubmit`
    /// implies the host-write barrier, so no flush and no `hipMemcpy` — the write is
    /// visible to any kernel submitted after it returns.
    pub fn write_at(&mut self, off: usize, bytes: &[u8]) -> Result<()> {
        // checked_add, not `off + len`: this is a SAFE fn, and in release `off` near
        // usize::MAX would wrap the sum to something small, pass the check, and let
        // copy_nonoverlapping write outside the mapping.
        ensure!(
            off.checked_add(bytes.len()).is_some_and(|e| e <= self.len),
            "write_at {off}+{} > buf len {}",
            bytes.len(),
            self.len
        );
        // SAFETY: the mapping covers `self.len`; `off+len` is within it (checked).
        unsafe { std::ptr::copy_nonoverlapping(bytes.as_ptr(), self.host.add(off), bytes.len()) };
        Ok(())
    }

    /// Read the first `len` bytes back into `out` (cleared, then refilled). Call after
    /// a [`device_sync`] — that is where the kernels' writes are made host-visible.
    pub fn read_into(&self, out: &mut Vec<u8>, len: usize) -> Result<()> {
        ensure!(len <= self.len, "read_into {len} > buf len {}", self.len);
        out.clear();
        out.reserve(len);
        // SAFETY: the mapping covers `self.len >= len`; `out` owns `len` reserved bytes.
        unsafe {
            std::ptr::copy_nonoverlapping(self.host, out.as_mut_ptr(), len);
            out.set_len(len);
        }
        Ok(())
    }
}

impl Drop for Buf {
    fn drop(&mut self) {
        let Ok(g) = gpu() else { return };
        // Flush first. Every buffer reaches the shader as a bare device address baked
        // into a push constant at RECORD time, so a dispatch recorded before this drop
        // still references these bytes — and because the address carries no object
        // identity, not even a validation layer could catch the use-after-free. A no-op
        // when nothing is recorded, which is the common case.
        if let Err(e) = g.sync() {
            warn!("Buf::drop: flush failed, freeing anyway: {e:#}");
        }
        // Deregister BEFORE the handles die, so `resolve` can never hand a freed
        // VkBuffer to vkCmdCopyBuffer. If the registry is unreachable we LEAK rather
        // than free: a stale entry pointing at a destroyed buffer is a use-after-free
        // with no object identity for any layer to catch, which is strictly worse than
        // an allocation that outlives its owner.
        match ALLOCS.lock() {
            Ok(mut allocs) => allocs.retain(|a| a.base != self.addr),
            Err(_) => {
                error!(
                    "vk alloc registry poisoned; LEAKING buffer at {:#x} rather than \
                     leaving a stale entry that resolve() could hand to a copy",
                    self.addr
                );
                return;
            }
        }
        // SAFETY: all three handles came from this device and are released once. The
        // caller's contract (see `device_sync`) is that no kernel still references them.
        unsafe {
            g.device.unmap_memory(self.mem);
            g.device.destroy_buffer(self.buf, None);
            g.device.free_memory(self.mem, None);
        }
    }
}

// ---------------------------------------------------------------------------
// Kernel launchers — the `hip.rs` surface, one fn per ported kernel.
// ---------------------------------------------------------------------------

/// Device-to-device copy of `bytes` from `src` to `dst` — the routed arena's slot
/// relocation (compaction). `hip::memcpy_dtod`'s twin, and like it this BLOCKS, so the
/// moved expert is in place before any later kernel reads the new slot.
///
/// # Safety
/// `dst` and `src` must be DEVICE ADDRESSES inside live [`Buf`]s, `bytes` long, and
/// NON-OVERLAPPING (the arena guarantees distinct slots).
pub unsafe fn memcpy_dtod(dst: *mut u8, src: *const u8, bytes: usize) -> Result<()> {
    ensure!(bytes > 0, "memcpy_dtod: argument guard rejected");
    let g = gpu()?;
    let (dbuf, doff) = resolve(dst as u64, bytes)?;
    let (sbuf, soff) = resolve(src as u64, bytes)?;
    let region = [vk::BufferCopy::default()
        .src_offset(soff)
        .dst_offset(doff)
        .size(bytes as u64)];
    g.enqueue(|d, cb| {
        // SAFETY: recording is open; both handles came from `resolve`, so each range
        // lies inside its buffer.
        unsafe { d.cmd_copy_buffer(cb, sbuf, dbuf, &region) };
    })?;
    g.sync()
}

/// Declare a `push_constant` mirror struct, with both of its invariants checked AT
/// COMPILE TIME rather than left as rules a porter has to remember at kernel 11 of 16:
///
/// - **No padding.** `dispatch` reads the struct as its own bytes; padding bytes are
///   uninitialised, and reading them as `u8` is UB. std430 would also place the
///   shader's fields differently than a padded Rust struct does, so the values would
///   silently land in the wrong slots. A `u64` after an `i32` introduces four bytes of
///   it, which is one field reorder away at every future launcher.
/// - **Fits the guaranteed budget.** 128 bytes is all Vulkan promises. Exceeding it is
///   the "push-constant budget" risk in docs/VULKAN.md; this makes it a build error
///   instead of a device-dependent surprise, so the params-buffer fallback gets built
///   the day it is actually needed and not before.
///
/// Order fields largest-first (8-byte device addresses, then 4-byte scalars) and the
/// no-padding check is satisfied naturally.
macro_rules! push_struct {
    ($(#[$m:meta])* $name:ident { $($(#[$fm:meta])* $f:ident: $t:ty),+ $(,)? }) => {
        $(#[$m])*
        #[repr(C)]
        struct $name { $($(#[$fm])* $f: $t),+ }
        const _: () = assert!(
            size_of::<$name>() == 0 $(+ size_of::<$t>())+,
            concat!(stringify!($name), " has padding: reorder fields largest-first"),
        );
        const _: () = assert!(
            size_of::<$name>() <= 128,
            concat!(stringify!($name), " exceeds the 128-byte guaranteed push budget"),
        );
    };
}

push_struct! {
    /// Mirror of `gemv_f32.comp`'s `push_constant` block. std430: three 8-byte buffer
    /// references then two ints — 32 bytes.
    GemvF32Push {
        x: u64,
        w: u64,
        y: u64,
        o_dim: i32,
        i_dim: i32,
    }
}

/// Workgroups needed to cover `n` elements at one element per invocation.
fn groups(n: usize) -> u32 {
    n.div_ceil(BLOCK as usize) as u32
}

/// A device address handed to a shader that reads or writes it as 32-bit WORDS must be
/// word-aligned, because the shader's offset arithmetic is relative to this base.
///
/// [`WORD`] and `DeviceTier::place` fix the LENGTH half of the word-addressing hazard;
/// this is the ALIGNMENT half. Every current caller satisfies it — `Buf` bases come
/// from `vkGetBufferDeviceAddress` and `place` results are 256-aligned — but the byte-
/// and u16-typed arguments (`packed`, `lc8`, `rc`) are exactly the shapes a caller
/// could hand a sub-pointer: a per-layer KV slab offset, a compacted arena slot. GPU-AV
/// checks out-of-bounds, not misalignment, so nothing else would catch it.
fn ensure_word_aligned(p: u64, what: &str) -> Result<()> {
    ensure!(
        (p as usize).is_multiple_of(WORD),
        "{what} address {p:#x} is not {WORD}-byte aligned — the shader reads it as \
         32-bit words, and its offsets are relative to this base"
    );
    Ok(())
}

/// f32 GEMV `y = W·x` (the MoE router gate).
///
/// # Safety
/// `x`, `w` and `y` must be DEVICE ADDRESSES of live [`Buf`] regions holding `i_dim`,
/// `o_dim·i_dim` and `o_dim` f32 respectively, and must stay live until the next
/// [`device_sync`].
pub unsafe fn launch_gemv_f32(
    x: *const f32,
    w: *const f32,
    o_dim: usize,
    i_dim: usize,
    y: *mut f32,
) -> Result<()> {
    ensure!(o_dim > 0 && i_dim > 0, "gemv_f32: argument guard rejected");
    let g = gpu()?;
    let push = GemvF32Push {
        x: x as u64,
        w: w as u64,
        y: y as u64,
        o_dim: o_dim as i32,
        i_dim: i_dim as i32,
    };
    g.dispatch(
        &g.pipes.gemv_f32,
        &push,
        o_dim.div_ceil(ROWS_PER_BLOCK as usize) as u32,
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn context_initialises() {
        let g = gpu().expect("vulkan init");
        let (free, total) = g.mem_info();
        println!(
            "\nVULKAN device: {} — {:.1} GiB device-local — validation layer: {}\n",
            g.name(),
            total as f64 / (1u64 << 30) as f64,
            if g.validation() { "ON" } else { "OFF (unvalidated!)" }
        );
        assert!(total > 0, "no DEVICE_LOCAL heap");
        // NOT `assert_eq!(free, total)`. That is what the stub used to return, and
        // asserting it encoded a bug as intent — `DeviceTier::new` gates the resident
        // tier on `free`, so free==total makes that guard always pass. The real
        // property is that free is a live figure below the heap size.
        assert!(free > 0 && free <= total, "free {free} total {total}");
        println!("VULKAN free: {:.1} GiB", free as f64 / (1u64 << 30) as f64);
        // Second call must hand back the same context, not build another.
        assert!(std::ptr::eq(g, gpu().expect("cached")));
    }
}

// ---------------------------------------------------------------------------
// Async-signal bridge — the timeline-semaphore replacement for hipLaunchHostFunc.
// ---------------------------------------------------------------------------

/// A one-shot completion shared between whatever resolves it and the future awaiting
/// it. Deliberately the SAME surface as `gpustream::Signal` — `pending`/`ready`/
/// `resolve` plus `Future` — so `asyncfetch.rs` and the expert stream in `gpu.rs` do
/// not change when the backend does.
#[derive(Clone)]
pub struct Signal(Arc<SignalState>);

struct SignalState {
    done: AtomicBool,
    waker: AtomicWaker,
}

impl Signal {
    /// An unresolved signal.
    pub fn pending() -> Self {
        Signal(Arc::new(SignalState {
            done: AtomicBool::new(false),
            waker: AtomicWaker::new(),
        }))
    }

    /// An already-resolved signal — a cache hit whose data is already present.
    pub fn ready() -> Self {
        let s = Self::pending();
        s.0.done.store(true, Ordering::Release);
        s
    }

    /// Force-resolve from the resolver side (an error path, so awaiters never hang).
    /// Idempotent.
    pub fn resolve(&self) {
        self.0.done.store(true, Ordering::Release);
        self.0.waker.wake();
    }
}

impl Future for Signal {
    type Output = ();
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        if self.0.done.load(Ordering::Acquire) {
            return Poll::Ready(());
        }
        self.0.waker.register(cx.waker());
        // Re-check: the waiter may have fired between the load and the register.
        if self.0.done.load(Ordering::Acquire) {
            Poll::Ready(())
        } else {
            Poll::Pending
        }
    }
}

/// The timeline semaphore plus the thread that watches it.
///
/// Vulkan has no host-callback-on-queue, which is what `hipLaunchHostFunc` gives the
/// HIP side (~19 us/signal). The replacement is one thread blocking in
/// `vkWaitSemaphores`, resolving every `Signal` whose value the counter has passed.
/// One thread total, not one per signal.
struct Timeline {
    sem: vk::Semaphore,
    /// Next value to signal. Monotonic; a timeline counter may only increase.
    next: AtomicU64,
    /// Registered `(value, signal)` pairs, and the condvar the waiter parks on when
    /// there is nothing outstanding.
    waiting: Mutex<Vec<(u64, Signal)>>,
    wake: Condvar,
}

impl Gpu {
    /// A [`Signal`] that resolves once everything SUBMITTED SO FAR has retired.
    ///
    /// ponytail: this covers submitted work, not work merely RECORDED into the open
    /// command buffer — it appends its own empty timeline-signal submit, and the queue
    /// is in-order, so it lands behind every prior submit. Recording is flushed by
    /// `device_sync`, so `device_sync()` then `signal()` is well defined today.
    ///
    /// Arming directly on top of recorded-but-unsubmitted work (what
    /// `Signal::arm_on(stream)` does on the HIP side) needs the single command buffer
    /// here to become a small ring, because an async flush cannot reuse a buffer that
    /// is still pending. That is integration-phase work: nothing consumes this yet,
    /// `asyncfetch.rs` being rocm-only, and building the ring before its consumer
    /// exists would be a design with no test to hold it honest.
    pub fn signal(&self) -> Result<Signal> {
        let t = &self.timeline;
        // The `cmd` mutex is held across allocate-value AND submit, for two reasons
        // that are both correctness, not tidiness:
        //
        //   MONOTONICITY. A timeline semaphore may only be signalled with a strictly
        //   increasing value. Allocating outside the lock lets two callers take 1 and
        //   2 and then submit in the order 2, 1 — which is a spec violation, not a
        //   reordering the driver will forgive. Allocating and submitting atomically
        //   makes submission order equal allocation order by construction.
        //
        //   QUEUE ACCESS. `vkQueueSubmit` requires the VkQueue to be externally
        //   synchronised, and `sync` submits under this same lock. Submitting here
        //   without it would let two threads call vkQueueSubmit on one queue.
        //
        // This is the lock the Send/Sync impl's invariant names, so taking it here is
        // what keeps that comment true rather than aspirational.
        ensure!(
            self.waiter.load(Ordering::Acquire),
            "timeline waiter thread never started, so no Signal can ever resolve; \
             refusing to hand out one that would hang its awaiter forever"
        );
        let cmd = self.cmd.lock().map_err(|_| anyhow!("vk command lock poisoned"))?;
        ensure!(
            !cmd.poisoned,
            "vk command buffer poisoned by an earlier device_sync failure"
        );
        let value = t.next.fetch_add(1, Ordering::Relaxed) + 1;
        let sig = Signal::pending();
        {
            let mut w = t
                .waiting
                .lock()
                .map_err(|_| anyhow!("vk timeline lock poisoned"))?;
            w.push((value, sig.clone()));
        }
        t.wake.notify_one();

        let sems = [t.sem];
        let values = [value];
        let mut ts = vk::TimelineSemaphoreSubmitInfo::default().signal_semaphore_values(&values);
        let submits = [vk::SubmitInfo::default()
            .signal_semaphores(&sems)
            .push_next(&mut ts)];
        // SAFETY: an empty submit that only signals. The queue's external-synchronisation
        // requirement is met by the `cmd` guard held above, which is the same lock
        // `sync` submits under.
        let r = unsafe { self.device.queue_submit(cmd.queue, &submits, vk::Fence::null()) };
        if let Err(e) = r {
            // Nothing will ever signal this value, so resolve it here rather than
            // leaving an awaiter parked forever.
            sig.resolve();
            if let Ok(mut w) = t.waiting.lock() {
                w.retain(|(v, _)| *v != value);
            }
            bail!("vkQueueSubmit (timeline signal) failed: {e}");
        }
        Ok(sig)
    }
}

impl Timeline {
    fn new(device: &ash::Device) -> Result<Self> {
        let mut ty = vk::SemaphoreTypeCreateInfo::default()
            .semaphore_type(vk::SemaphoreType::TIMELINE)
            .initial_value(0);
        let ci = vk::SemaphoreCreateInfo::default().push_next(&mut ty);
        // SAFETY: `device` is live; `ci` outlives the call.
        let sem = unsafe { device.create_semaphore(&ci, None) }?;
        Ok(Self {
            sem,
            next: AtomicU64::new(0),
            waiting: Mutex::new(Vec::new()),
            wake: Condvar::new(),
        })
    }
}

/// The waiter thread: block until the counter passes the lowest outstanding value,
/// then resolve everything it has reached. Runs for the life of the process.
fn timeline_waiter(g: &'static Gpu) {
    /// Consecutive 100 ms timeouts on the same value before saying so — 5 s.
    const STALL_WARN: u32 = 50;
    let t = &g.timeline;
    let mut stalls = 0u32;
    loop {
        // Park while nothing is outstanding, so an idle process costs no CPU.
        let target = {
            let Ok(mut w) = t.waiting.lock() else { return };
            while w.is_empty() {
                let Ok(next) = t.wake.wait(w) else { return };
                w = next;
            }
            w.iter().map(|(v, _)| *v).min().unwrap_or(u64::MAX)
        };
        let sems = [t.sem];
        let values = [target];
        let info = vk::SemaphoreWaitInfo::default()
            .semaphores(&sems)
            .values(&values);
        // A timeout rather than u64::MAX, so a stuck submit cannot wedge this thread.
        // SAFETY: `t.sem` is live for the process.
        let waited = unsafe { g.device.wait_semaphores(&info, 100_000_000) };
        // TIMEOUT and a real error MUST be told apart. ash maps every non-SUCCESS code
        // to Err, and on VK_ERROR_DEVICE_LOST the wait returns IMMEDIATELY — so
        // discarding the result and looping turns the one failure the timeout exists to
        // bound into a thread spinning a full core forever while every awaiter stays
        // parked. Discarding it with `let _` also throws away the only thing that could
        // distinguish the two.
        match waited {
            Ok(()) | Err(vk::Result::TIMEOUT) => {}
            Err(e) => {
                error!("vk timeline wait failed ({e}); resolving all awaiters and stopping");
                if let Ok(mut w) = t.waiting.lock() {
                    for (_, s) in w.drain(..) {
                        s.resolve();
                    }
                }
                return;
            }
        }
        // SAFETY: as above.
        let now = match unsafe { g.device.get_semaphore_counter_value(t.sem) } {
            Ok(v) => v,
            Err(e) => {
                error!("vk timeline counter read failed ({e}); resolving all awaiters");
                if let Ok(mut w) = t.waiting.lock() {
                    for (_, s) in w.drain(..) {
                        s.resolve();
                    }
                }
                return;
            }
        };
        // A value that is submitted but never signalled would otherwise sit at the head
        // of the queue forever: `target` is the minimum, so every later signal would
        // wait the full 100 ms before the sweep below reached it — a permanent, silent
        // latency collapse from ~50 us to 100 ms. Say so instead of degrading quietly.
        if waited == Err(vk::Result::TIMEOUT) {
            stalls += 1;
            if stalls == STALL_WARN {
                warn!(
                    "vk timeline value {target} has not been signalled after {} s; \
                     every later Signal is now paying the full wait timeout",
                    STALL_WARN / 10
                );
            }
        } else {
            stalls = 0;
        }
        let Ok(mut w) = t.waiting.lock() else { return };
        // Resolve OUTSIDE the retain predicate's borrow of the signal, and resolve
        // every value the counter has passed, not just `target` — several may have
        // landed inside one wait.
        let mut fired = Vec::new();
        w.retain(|(v, s)| {
            if *v <= now {
                fired.push(s.clone());
                false
            } else {
                true
            }
        });
        drop(w);
        for s in fired {
            s.resolve();
        }
    }
}

// --- fwd.hip tranche -------------------------------------------------------

push_struct! {
    /// Mirror of `embed_i8_row.comp`'s push block.
    EmbedI8Push {
        packed: u64,
        scale: u64,
        x: u64,
        token: i32,
        hidden: i32,
    }
}

/// Embedding row lookup `x[i] = (i8)packed[token*hidden + i] * scale[token]`.
///
/// # Safety
/// Device addresses of live [`Buf`]s, valid until the next [`device_sync`]: `packed`
/// (`>= (token+1)*hidden` bytes), `scale` (`> token` f32), `x` (`hidden` f32).
pub unsafe fn launch_embed_i8_row(
    packed: *const u8,
    scale: *const f32,
    token: usize,
    hidden: usize,
    x: *mut f32,
) -> Result<()> {
    ensure!(hidden > 0, "embed_i8_row: argument guard rejected");
    ensure_word_aligned(packed as u64, "embed_i8_row packed")?;
    let g = gpu()?;
    let push = EmbedI8Push {
        packed: packed as u64,
        scale: scale as u64,
        x: x as u64,
        token: token as i32,
        hidden: hidden as i32,
    };
    g.dispatch(&g.pipes.embed_i8_row, &push, groups(hidden))
}

push_struct! {
    /// Mirror of `append_kv.comp`'s push block.
    AppendKvPush {
        latent: u64,
        rope: u64,
        lc8: u64,
        lscale: u64,
        rc: u64,
        pos: i32,
        kvl: i32,
        ropn: i32,
        n_blocks: i32,
        /// Passed at runtime so `glslc -O` cannot fold `a / 448.0` into a multiply by
        /// fl(1/448) — see the note in append_kv.comp.
        e4m3_max: f32,
        _pad: u32,
    }
}

/// Append one token's latent (fp8-e4m3 + per-128 block scale) and roped key (bf16) at
/// row `pos`.
///
/// # Safety
/// Device addresses of live [`Buf`]s, valid until the next [`device_sync`]: `latent`
/// (`kvl` f32), `rope` (`ropn` f32), `lc8` (`(pos+1)*kvl` bytes), `lscale`
/// (`(pos+1)*n_blocks` f32), `rc` (`(pos+1)*ropn` u16).
#[allow(clippy::too_many_arguments)]
pub unsafe fn launch_append_kv(
    latent: *const f32,
    rope: *const f32,
    lc8: *mut u8,
    lscale: *mut f32,
    rc: *mut u16,
    pos: usize,
    kvl: usize,
    ropn: usize,
    n_blocks: usize,
) -> Result<()> {
    ensure!(
        kvl > 0 && ropn > 0 && n_blocks > 0,
        "append_kv: argument guard rejected"
    );
    // Same envelope as the HIP guard: the per-128 reduction needs kvl a multiple of 128
    // in [128, 1024]. Here 1024 is also MAX_BLOCKS*128, one 128-block per subgroup.
    // DERIVED from the shader's geometry, not hardcoded: append_kv.comp maps one
    // 128-element block per subgroup, so the ceiling is one block per subgroup in the
    // workgroup. A `#if` in the shader fails the build if these two drift apart.
    const KV_BLOCK: usize = 128;
    let kvl_max = ROWS_PER_BLOCK as usize * KV_BLOCK;
    ensure!(
        (KV_BLOCK..=kvl_max).contains(&kvl) && kvl.is_multiple_of(KV_BLOCK) && ropn <= kvl,
        "append_kv: kvl {kvl} must be a multiple of {KV_BLOCK} in [{KV_BLOCK},{kvl_max}] \
         and ropn {ropn} <= kvl"
    );
    ensure!(
        n_blocks == kvl / KV_BLOCK,
        "append_kv: n_blocks {n_blocks} != kvl/{KV_BLOCK} ({})",
        kvl / KV_BLOCK
    );
    // STRICTER THAN THE HIP GUARD, on purpose. `rc` is u16 and this shader writes it as
    // packed u32 words, so both the row base (pos*ropn) and the element count must be
    // even or a word write would straddle two keys and the odd tail would be dropped.
    // The HIP kernel writes u16 directly and does not care. Every real ropn is even (it
    // is a rope dimension), so this is a loud refusal for a case that does not occur
    // rather than a silently different result — which is the failure mode that matters
    // when the two backends are supposed to agree bit for bit.
    ensure!(
        ropn.is_multiple_of(2),
        "append_kv: ropn {ropn} must be even under the Vulkan backend (u16 keys are \
         written as packed u32 words); the HIP backend accepts odd ropn"
    );
    ensure_word_aligned(lc8 as u64, "append_kv lc8")?;
    ensure_word_aligned(rc as u64, "append_kv rc")?;
    let g = gpu()?;
    let push = AppendKvPush {
        latent: latent as u64,
        rope: rope as u64,
        lc8: lc8 as u64,
        lscale: lscale as u64,
        rc: rc as u64,
        pos: pos as i32,
        kvl: kvl as i32,
        ropn: ropn as i32,
        n_blocks: n_blocks as i32,
        e4m3_max: crate::math::E4M3_MAX,
        _pad: 0,
    };
    // One workgroup, like the HIP launch: the per-block reduction is workgroup-local.
    g.dispatch(&g.pipes.append_kv, &push, 1)
}

push_struct! {
    /// Mirror of `gather_rope.comp`'s push block.
    GatherRopePush {
        q: u64,
        qrope: u64,
        h: i32,
        qh: i32,
        nope: i32,
        ropn: i32,
    }
}

/// Gather each head's roped query segment: `qrope[head*ropn + d] = q[head*qh + nope + d]`.
///
/// # Safety
/// Device addresses of live [`Buf`]s, valid until the next [`device_sync`]: `q`
/// (`h*qh` f32), `qrope` (`h*ropn` f32).
pub unsafe fn launch_gather_rope(
    q: *const f32,
    qrope: *mut f32,
    h: usize,
    qh: usize,
    nope: usize,
    ropn: usize,
) -> Result<()> {
    ensure!(
        h > 0 && qh > 0 && ropn > 0 && nope + ropn <= qh,
        "gather_rope: argument guard rejected"
    );
    let g = gpu()?;
    let push = GatherRopePush {
        q: q as u64,
        qrope: qrope as u64,
        h: h as i32,
        qh: qh as i32,
        nope: nope as i32,
        ropn: ropn as i32,
    };
    g.dispatch(&g.pipes.gather_rope, &push, groups(h * ropn))
}

push_struct! {
    /// Mirror of `vadd.comp`'s push block. `_pad` keeps the struct padding-free so
    /// `push_struct!`'s assertion holds; the shader simply does not read it.
    VaddPush {
        x: u64,
        y: u64,
        n: i32,
        _pad: i32,
    }
}

/// Residual add `x[i] += y[i]`, in place.
///
/// # Safety
/// Device addresses of live [`Buf`]s holding `n` f32 each, valid until the next
/// [`device_sync`].
pub unsafe fn launch_vadd(x: *mut f32, y: *const f32, n: usize) -> Result<()> {
    ensure!(n > 0, "vadd: argument guard rejected");
    let g = gpu()?;
    let push = VaddPush {
        x: x as u64,
        y: y as u64,
        n: n as i32,
        _pad: 0,
    };
    g.dispatch(&g.pipes.vadd, &push, groups(n))
}

push_struct! {
    /// Mirror of `argmax_reduce.comp`'s push block.
    ArgmaxPush {
        logits: u64,
        out_idx: u64,
        out_val: u64,
        n: i32,
        _pad: i32,
    }
}

/// Greedy argmax over `logits[0..n]` → (`out_idx`, `out_val`); lowest index on a tie,
/// NaN never wins (matches the host fold in `gpu.rs::argmax`).
///
/// # Safety
/// Device addresses of live [`Buf`]s, valid until the next [`device_sync`]: `logits`
/// (`n` f32), `out_idx` (one i32), `out_val` (one f32).
pub unsafe fn launch_argmax(
    logits: *const f32,
    n: usize,
    out_idx: *mut i32,
    out_val: *mut f32,
) -> Result<()> {
    ensure!(n > 0, "argmax: argument guard rejected");
    let g = gpu()?;
    let push = ArgmaxPush {
        logits: logits as u64,
        out_idx: out_idx as u64,
        out_val: out_val as u64,
        n: n as i32,
        _pad: 0,
    };
    // ONE workgroup: the reduction is workgroup-local and the grid-stride loop inside
    // covers any n. Matches the HIP launch.
    g.dispatch(&g.pipes.argmax_reduce, &push, 1)
}
