//! The Vulkan compute backend — the `rocm`-free twin of `hip.rs`. Instance/device
//! bring-up, memory, queue/timeline sync, and the `launch_*` surface over the SPIR-V
//! kernels in `kernels/vk/`. See docs/VULKAN.md.
//!
//! Everything hangs off one process-global [`Gpu`]. HIP hides its context inside the
//! runtime, which is why `hip.rs`'s launchers and `device.rs`'s buffers take nothing
//! but pointers; keeping ours global buys the same signatures, so `gpu.rs` and
//! `pin.rs` never learn a backend exists.

#![cfg(feature = "vulkan")]

use anyhow::{Result, anyhow, bail, ensure};
use ash::vk;
use std::ffi::CStr;
use std::sync::{Mutex, OnceLock};
use tracing::{info, warn};

const VALIDATION_LAYER: &CStr = c"VK_LAYER_KHRONOS_validation";

// `WAVE` and `ROWS_PER_BLOCK`, generated by build.rs from the same constants it
// passes to glslc with -D. Declaring them here as well and hoping the two stay equal
// is what HIP avoids by deriving ROW_GRID/ROW_BLOCK from one common.hpp define: a
// mismatch dispatches too few workgroups and the unwritten output rows keep their old
// contents — no fault, and no validation diagnostic either.
//
// WAVE is 32 because gfx1151 is native wave32; the pipelines pin it with
// `requiredSubgroupSize` + REQUIRE_FULL_SUBGROUPS, so a driver that cannot honour it
// fails at init rather than silently reducing gl_NumSubgroups (which would leave the
// upper rows of every workgroup unwritten — see gemv_f32.comp).
include!(concat!(env!("OUT_DIR"), "/dims.rs"));

/// Threads per workgroup. The shaders' `local_size_x`.
pub const BLOCK: u32 = ROWS_PER_BLOCK * WAVE;

/// Instance, device, the dedicated compute queue, and a command pool on it. Built
/// once by [`gpu`]; never dropped (see the note there).
pub struct Gpu {
    pub device: ash::Device,
    pub memprops: vk::PhysicalDeviceMemoryProperties,
    queue: vk::Queue,
    instance: ash::Instance,
    phys: vk::PhysicalDevice,
    /// Owns the dlopen'd libvulkan; must outlive the instance, never called through.
    _entry: ash::Entry,
    cmd: Mutex<Cmd>,
    pipes: Pipes,
    validation: bool,
    budget: bool,
}

/// Count of validation ERROR/WARNING messages seen. Tests assert it is zero, so a
/// layer diagnostic FAILS THE RUN instead of scrolling past in a log nobody reads.
pub static VALIDATION_ERRORS: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(0);

unsafe extern "system" fn debug_callback(
    sev: vk::DebugUtilsMessageSeverityFlagsEXT,
    ty: vk::DebugUtilsMessageTypeFlagsEXT,
    data: *const vk::DebugUtilsMessengerCallbackDataEXT<'_>,
    _user: *mut std::ffi::c_void,
) -> vk::Bool32 {
    // SAFETY: the loader guarantees `data` points at a valid struct for this call.
    let msg = unsafe { (*data).message_as_c_str() }
        .unwrap_or(c"<no message>")
        .to_string_lossy()
        .into_owned();
    let err = sev.contains(vk::DebugUtilsMessageSeverityFlagsEXT::ERROR);
    // SAFETY: the loader guarantees `data` points at a valid struct for this call.
    let id = unsafe { (*data).message_id_name_as_c_str() }
        .unwrap_or(c"")
        .to_string_lossy()
        .into_owned();
    // Two classes are logged but NOT counted, because counting them would make the
    // assertion fire on something that is not a finding — and an assertion that cries
    // wolf gets deleted rather than triaged.
    //
    //   PERFORMANCE — advice, not misuse ("your dispatch is small").
    //   The layer talking ABOUT ITSELF — enabling GPU-AV makes it emit
    //   VALIDATION-SETTINGS ("GPU-AV and core both on is slow") and
    //   WARNING-Setting-Limit-Adjusted ("forcing vulkanMemoryModel to TRUE so I can
    //   instrument your shaders"). Those describe the checker's configuration, not our
    //   Vulkan usage, and without this the suite can NEVER pass under GPU-AV — which
    //   is the one checker that covers the bare-device-address design.
    //
    // Matched by exact message-ID name, not a substring of the body: narrow enough
    // that a real finding cannot hide behind it.
    let self_report = matches!(
        id.as_str(),
        "VALIDATION-SETTINGS" | "WARNING-Setting-Limit-Adjusted"
    );
    if !ty.contains(vk::DebugUtilsMessageTypeFlagsEXT::PERFORMANCE) && !self_report {
        VALIDATION_ERRORS.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }
    // stderr UNCONDITIONALLY, in addition to `tracing`.
    //
    // Not belt-and-braces: `tracing` alone is a NULL SINK in the binary that matters.
    // The test harness installs no subscriber, so the counter above would move while
    // the message text vanished — a validation failure would report as a bare number
    // with no way to learn what the layer said, and the counter moving would make the
    // messenger look like it worked. The alternative fix (install a subscriber in the
    // test binary) leaves the same hole for anything else that links this crate
    // without one. eprintln has no such dependency.
    let level = if err { "ERROR" } else { "WARNING" };
    eprintln!("vk validation {level}: {msg}");
    if err {
        tracing::error!("vk validation: {msg}");
    } else {
        warn!("vk validation: {msg}");
    }
    vk::FALSE
}

/// The one open command buffer every `launch_*` appends to, plus the fence
/// [`device_sync`] joins on. Mirrors HIP's default stream: launches queue up, the
/// sync submits and waits. One buffer, reset and refilled — no per-launch submit
/// (colibri measured submit cost as the thing that matters on RADV).
struct Cmd {
    pool: vk::CommandPool,
    buf: vk::CommandBuffer,
    fence: vk::Fence,
    recording: bool,
    /// Set by any failure in [`Gpu::sync`]. Each of its fallible calls leaves the
    /// buffer in a DIFFERENT illegal state — invalid after a failed `end`, executable
    /// after a failed submit, *pending* after a failed fence wait — and the pool has
    /// no `RESET_COMMAND_BUFFER` bit, so `vkBeginCommandBuffer` is only legal from the
    /// initial state. Since `device_sync` returns a `Result` the engine can observe
    /// the error and carry on, which would put every later submit into undefined
    /// behaviour, silently, with no validation layer to say so. So the failure is
    /// STICKY: once poisoned, nothing is recorded or submitted again.
    poisoned: bool,
}

/// A compiled compute kernel. Every pipeline here has an EMPTY descriptor-set layout:
/// buffers reach the shader as device addresses in push constants, which is HIP's raw
/// pointer args translated literally (docs/VULKAN.md, "kernel raw pointer args").
struct Pipe {
    layout: vk::PipelineLayout,
    pipe: vk::Pipeline,
    /// Bytes the layout declares. `dispatch` asserts the push struct matches: pushing
    /// more than the range is a VUID violation with nothing else to catch it.
    push_size: u32,
}

/// Every kernel, compiled once at init. Grows one field per ported kernel.
struct Pipes {
    gemv_f32: Pipe,
}

// SAFETY: needed because ash models the DISPATCHABLE handles (`vk::Queue`,
// `vk::CommandBuffer`) as raw pointers, hence `!Send`/`!Sync`; the non-dispatchable
// ones are `u64` and already fine.
//
// The invariant is CHECKABLE rather than merely asserted: the handles Vulkan requires
// to be externally synchronised are the queue and the command pool/buffer, `queue` is
// a PRIVATE field, `Cmd` is a private type behind `self.cmd`, and the only code that
// touches either is `Gpu::enqueue`/`Gpu::sync` — both of which hold the `cmd` mutex
// for their whole body. `device` is public but `VkDevice` is internally synchronised.
// Keep `queue` private: a `pub` queue would let any caller submit concurrently from a
// second thread and this comment would become a lie.
unsafe impl Send for Gpu {}
unsafe impl Sync for Gpu {}

static GPU: OnceLock<Gpu> = OnceLock::new();

/// The process-global context, built on first use.
///
/// Not dropped: it lives until exit, and tearing a Vulkan device down while the
/// engine's buffers (also static-lifetime, also never freed on the HIP side) still
/// hold handles would be strictly worse than letting the OS reclaim it.
pub fn gpu() -> Result<&'static Gpu> {
    // Double-checked: the fast path is a plain atomic load, and the slow path is
    // taken once per process. `OnceLock::get_or_init` alone would be wrong here —
    // `Gpu::new` is fallible, so init has to happen outside the closure, and two
    // threads racing would each build a whole VkInstance + VkDevice + pipeline set
    // with the loser's LEAKED (Gpu has no Drop, deliberately). The decode loop is
    // single-threaded so this never fires in the engine, but cargo's test harness
    // runs tests in parallel threads and every one of them calls `gpu()`.
    //
    // No deadlock surface: nothing reachable from `Gpu::new` calls `gpu()`.
    if let Some(g) = GPU.get() {
        return Ok(g);
    }
    static INIT: Mutex<()> = Mutex::new(());
    let _lk = INIT.lock().map_err(|_| anyhow!("vk init lock poisoned"))?;
    if let Some(g) = GPU.get() {
        return Ok(g);
    }
    let g = Gpu::new()?;
    Ok(GPU.get_or_init(|| g))
}

impl Gpu {
    fn new() -> Result<Self> {
        // SAFETY: loads libvulkan; the returned Entry owns it for the process.
        let entry = unsafe { ash::Entry::load() }
            .map_err(|e| anyhow::anyhow!("no Vulkan loader: {e}"))?;

        let app = vk::ApplicationInfo::default()
            .application_name(c"rivoli")
            .api_version(vk::API_VERSION_1_3);
        let validation = Self::validation_layer(&entry);
        let all = [VALIDATION_LAYER.as_ptr()];
        // VK_EXT_debug_utils is what carries the layer's diagnostics to us. Without a
        // messenger, "validation ENABLED" would mean the layer talks to a settings
        // file and nothing else — reaching neither `tracing` nor a test assertion,
        // which is the same "green run mistaken for a validated one" the layer is
        // supposed to prevent. The extension is provided by the loader independently
        // of the layer, so we ask for it whenever it is advertised.
        let debug = Self::has_extension(&entry, ash::ext::debug_utils::NAME);
        let exts = [ash::ext::debug_utils::NAME.as_ptr()];
        let ci = vk::InstanceCreateInfo::default()
            .application_info(&app)
            .enabled_layer_names(&all[..validation as usize])
            .enabled_extension_names(&exts[..debug as usize]);
        // SAFETY: `ci` and everything it borrows outlive the call.
        let instance = unsafe { entry.create_instance(&ci, None) }?;
        if debug {
            Self::attach_messenger(&entry, &instance)?;
        }

        let (phys, qfam) = Self::pick(&instance)?;
        // Live free-memory reporting; see `mem_info`. Optional because the fallback
        // (free == total) is merely useless, not wrong.
        let budget = Self::has_device_extension(&instance, phys, ash::ext::memory_budget::NAME);
        let device = Self::create_device(&instance, phys, qfam, budget)?;
        // SAFETY: `qfam` came from the queue-create-info above; index 0 exists.
        let queue = unsafe { device.get_device_queue(qfam, 0) };
        // SAFETY: `phys` is a live physical device from this instance.
        let memprops = unsafe { instance.get_physical_device_memory_properties(phys) };
        let cmd = Cmd::new(&device, qfam)?;
        let pipes = Pipes::new(&device)?;

        Ok(Self {
            device,
            queue,
            memprops,
            instance,
            phys,
            _entry: entry,
            cmd: Mutex::new(cmd),
            pipes,
            validation,
            budget,
        })
    }

    /// Is `VK_LAYER_KHRONOS_validation` installed? Says so either way, at WARN when
    /// it is not — same rule as `device.rs`'s sole-tenant guard: a silently-inert
    /// safety net is worse than none, because you believe you are protected.
    ///
    /// This backend passes every buffer as a raw device address with no descriptor
    /// sets, and a bad address or a missing barrier reads plausible GARBAGE rather
    /// than faulting. The validation layer is the only thing that catches that class;
    /// `spirv-val` (run by build.rs) checks module wellformedness, not API use.
    fn validation_layer(entry: &ash::Entry) -> bool {
        // SAFETY: the loader is live.
        let Ok(layers) = (unsafe { entry.enumerate_instance_layer_properties() }) else {
            warn!("VULKAN VALIDATION OFF: could not enumerate instance layers");
            return false;
        };
        let found = layers.iter().any(|l| {
            l.layer_name_as_c_str()
                .is_ok_and(|n| n == VALIDATION_LAYER)
        });
        if found {
            info!("Vulkan validation layer ENABLED");
        } else {
            warn!(
                "VULKAN VALIDATION OFF: {} not installed. Buffer-device-address and \
                 synchronisation misuse will read garbage instead of failing.",
                VALIDATION_LAYER.to_string_lossy()
            );
        }
        found
    }

    fn has_extension(entry: &ash::Entry, name: &CStr) -> bool {
        // SAFETY: the loader is live.
        unsafe { entry.enumerate_instance_extension_properties(None) }
            .is_ok_and(|xs| xs.iter().any(|x| x.extension_name_as_c_str() == Ok(name)))
    }

    /// Route the validation layer's ERROR/WARNING messages into `tracing` and count
    /// them, so a diagnostic can FAIL A TEST rather than scroll past. Without this the
    /// layer's output goes wherever its settings file says, which is nowhere useful.
    fn attach_messenger(entry: &ash::Entry, instance: &ash::Instance) -> Result<()> {
        use vk::DebugUtilsMessageSeverityFlagsEXT as Sev;
        use vk::DebugUtilsMessageTypeFlagsEXT as Ty;
        let ci = vk::DebugUtilsMessengerCreateInfoEXT::default()
            .message_severity(Sev::ERROR | Sev::WARNING)
            .message_type(Ty::GENERAL | Ty::VALIDATION | Ty::PERFORMANCE)
            .pfn_user_callback(Some(debug_callback));
        let dbg = ash::ext::debug_utils::Instance::new(entry, instance);
        // SAFETY: `instance` is live and `ci` outlives the call. The messenger is
        // never destroyed — it must outlive every other object, and the instance is
        // itself never destroyed (see `gpu`).
        unsafe { dbg.create_debug_utils_messenger(&ci, None) }?;
        Ok(())
    }

    /// Whether this context is running under the validation layer. Tests print it so
    /// a green run is never mistaken for a validated one.
    pub fn validation(&self) -> bool {
        self.validation
    }

    /// First physical device whose queue families and features satisfy the whole
    /// contract. If none does, report EVERY missing item for the *last* candidate
    /// rather than a bare "no suitable device" — on a one-GPU box that is the answer.
    fn pick(instance: &ash::Instance) -> Result<(vk::PhysicalDevice, u32)> {
        // SAFETY: `instance` is live.
        let devices = unsafe { instance.enumerate_physical_devices() }?;
        let mut last: Option<(String, Vec<String>)> = None;
        for phys in devices {
            // SAFETY: `phys` came from this instance.
            let props = unsafe { instance.get_physical_device_properties(phys) };
            let name = props.device_name_as_c_str().map_or_else(
                |_| "<unnamed>".to_string(),
                |s| s.to_string_lossy().into_owned(),
            );
            let mut missing = Vec::new();
            if props.api_version < vk::API_VERSION_1_3 {
                missing.push(format!(
                    "Vulkan 1.3 (device reports {}.{})",
                    vk::api_version_major(props.api_version),
                    vk::api_version_minor(props.api_version)
                ));
            }
            let qfam = Self::compute_queue(instance, phys);
            if qfam.is_none() {
                missing.push("a COMPUTE queue family".into());
            }
            missing.extend(Self::missing_features(instance, phys));
            match (qfam, missing.is_empty()) {
                (Some(q), true) => return Ok((phys, q)),
                _ => last = Some((name, missing)),
            }
        }
        match last {
            Some((name, missing)) => bail!(
                "no Vulkan device meets the rivoli contract; closest was {name}, missing: {}",
                missing.join(", ")
            ),
            None => bail!("no Vulkan physical devices found"),
        }
    }

    /// A DEDICATED compute family (COMPUTE without GRAPHICS) if the device has one,
    /// else any COMPUTE family. Colibri measured the dedicated queue as the better
    /// choice on RADV (commit 4d4cacc) — it does not contend with the compositor.
    fn compute_queue(instance: &ash::Instance, phys: vk::PhysicalDevice) -> Option<u32> {
        // SAFETY: `phys` came from `instance`.
        let fams = unsafe { instance.get_physical_device_queue_family_properties(phys) };
        let compute =
            |f: &vk::QueueFamilyProperties| f.queue_flags.contains(vk::QueueFlags::COMPUTE);
        fams.iter()
            .position(|f| compute(f) && !f.queue_flags.contains(vk::QueueFlags::GRAPHICS))
            .or_else(|| fams.iter().position(compute))
            .map(|i| i as u32)
    }

    /// Every required feature the device lacks, named as the spec names it so the
    /// failure is actionable. Fail fast beats a mystery `VK_ERROR_DEVICE_LOST` later.
    fn missing_features(instance: &ash::Instance, phys: vk::PhysicalDevice) -> Vec<String> {
        let mut v11 = vk::PhysicalDeviceVulkan11Features::default();
        let mut v12 = vk::PhysicalDeviceVulkan12Features::default();
        let mut v13 = vk::PhysicalDeviceVulkan13Features::default();
        // Scoped so the pNext chain's mutable borrows end and the filled-in structs
        // can be read below.
        let core = {
            let mut f2 = vk::PhysicalDeviceFeatures2::default()
                .push_next(&mut v11)
                .push_next(&mut v12)
                .push_next(&mut v13);
            // SAFETY: `phys` is live; the chain is valid for the duration of the call.
            unsafe { instance.get_physical_device_features2(phys, &mut f2) };
            f2.features
        };

        let mut sub = vk::PhysicalDeviceSubgroupProperties::default();
        let mut size = vk::PhysicalDeviceSubgroupSizeControlProperties::default();
        let p2 = {
            let mut p2 = vk::PhysicalDeviceProperties2::default()
                .push_next(&mut sub)
                .push_next(&mut size);
            // SAFETY: as above.
            unsafe { instance.get_physical_device_properties2(phys, &mut p2) };
            vk::PhysicalDeviceProperties2 {
                properties: p2.properties,
                ..Default::default()
            }
        };

        let mut missing = Vec::new();
        let mut need = |ok: bool, what: &str| {
            if !ok {
                missing.push(what.to_string());
            }
        };
        // Lets ExpertDesc's six raw pointers stay six uint64 addresses in a push
        // constant instead of six descriptor bindings rewritten per expert.
        need(v12.buffer_device_address == vk::TRUE, "bufferDeviceAddress");
        // ...which the shader dereferences as uint64_t buffer references.
        need(core.shader_int64 == vk::TRUE, "shaderInt64");
        need(v12.timeline_semaphore == vk::TRUE, "timelineSemaphore");
        // The fp16 VQ codebook.
        need(v12.shader_float16 == vk::TRUE, "shaderFloat16");
        need(v11.storage_buffer16_bit_access == vk::TRUE, "storageBuffer16BitAccess");
        // WAVE 32 is not negotiable — the reductions are a fixed 32-lane ladder.
        need(v13.subgroup_size_control == vk::TRUE, "subgroupSizeControl");
        need(v13.compute_full_subgroups == vk::TRUE, "computeFullSubgroups");
        need(
            size.min_subgroup_size <= WAVE && WAVE <= size.max_subgroup_size,
            &format!(
                "a subgroup size of {WAVE} (device allows {}..={})",
                size.min_subgroup_size, size.max_subgroup_size
            ),
        );
        need(
            size.required_subgroup_size_stages.contains(vk::ShaderStageFlags::COMPUTE),
            "requiredSubgroupSizeStages including COMPUTE",
        );
        need(
            sub.supported_stages.contains(vk::ShaderStageFlags::COMPUTE),
            "subgroup operations in COMPUTE",
        );
        // The shaders declare local_size_x = BLOCK. Vulkan only GUARANTEES 128
        // invocations and (128,128,64), both below the 256 we need, so a conformant
        // minimum-limits device would fail vkCreateComputePipelines with an opaque
        // ERROR_INITIALIZATION_FAILED instead of naming the limit. gfx1151 allows
        // 1024; the point of this function is the machines that are not gfx1151.
        let lim = p2.properties.limits;
        need(
            lim.max_compute_work_group_invocations >= BLOCK,
            &format!(
                "maxComputeWorkGroupInvocations >= {BLOCK} (device allows {})",
                lim.max_compute_work_group_invocations
            ),
        );
        need(
            lim.max_compute_work_group_size[0] >= BLOCK,
            &format!(
                "maxComputeWorkGroupSize[0] >= {BLOCK} (device allows {})",
                lim.max_compute_work_group_size[0]
            ),
        );
        // VUID-VkPipelineShaderStageCreateInfo-pNext-02759: local_size_x must fit in
        // maxComputeWorkgroupSubgroups * requiredSubgroupSize.
        need(
            size.max_compute_workgroup_subgroups >= ROWS_PER_BLOCK,
            &format!(
                "maxComputeWorkgroupSubgroups >= {ROWS_PER_BLOCK} (device allows {})",
                size.max_compute_workgroup_subgroups
            ),
        );
        for (flag, name) in [
            (vk::SubgroupFeatureFlags::BASIC, "subgroup BASIC"),
            (vk::SubgroupFeatureFlags::SHUFFLE_RELATIVE, "subgroup SHUFFLE_RELATIVE"),
        ] {
            need(sub.supported_operations.contains(flag), name);
        }
        // On Strix Halo host RAM *is* GPU memory (GTT); the pin path writes resident
        // weights straight into device-local memory, so this heap must exist.
        // SAFETY: `phys` is live.
        let mp = unsafe { instance.get_physical_device_memory_properties(phys) };
        let want = vk::MemoryPropertyFlags::DEVICE_LOCAL | vk::MemoryPropertyFlags::HOST_VISIBLE;
        need(
            mp.memory_types[..mp.memory_type_count as usize]
                .iter()
                .any(|t| t.property_flags.contains(want)),
            "a DEVICE_LOCAL | HOST_VISIBLE memory type",
        );
        missing
    }

    fn has_device_extension(
        instance: &ash::Instance,
        phys: vk::PhysicalDevice,
        name: &CStr,
    ) -> bool {
        // SAFETY: `phys` came from `instance`.
        unsafe { instance.enumerate_device_extension_properties(phys) }
            .is_ok_and(|xs| xs.iter().any(|x| x.extension_name_as_c_str() == Ok(name)))
    }

    fn create_device(
        instance: &ash::Instance,
        phys: vk::PhysicalDevice,
        qfam: u32,
        budget: bool,
    ) -> Result<ash::Device> {
        let prio = [1.0f32];
        let qci = [vk::DeviceQueueCreateInfo::default()
            .queue_family_index(qfam)
            .queue_priorities(&prio)];
        let mut v11 = vk::PhysicalDeviceVulkan11Features::default().storage_buffer16_bit_access(true);
        let mut v12 = vk::PhysicalDeviceVulkan12Features::default()
            .buffer_device_address(true)
            .timeline_semaphore(true)
            .shader_float16(true);
        let mut v13 = vk::PhysicalDeviceVulkan13Features::default()
            .subgroup_size_control(true)
            .compute_full_subgroups(true);
        let core = vk::PhysicalDeviceFeatures::default().shader_int64(true);
        // Every REQUIRED extension is core in 1.3 — including subgroup_size_control
        // and buffer_device_address. memory_budget is the one optional extra.
        let exts = [ash::ext::memory_budget::NAME.as_ptr()];
        let ci = vk::DeviceCreateInfo::default()
            .queue_create_infos(&qci)
            .enabled_extension_names(&exts[..budget as usize])
            .enabled_features(&core)
            .push_next(&mut v11)
            .push_next(&mut v12)
            .push_next(&mut v13);
        // SAFETY: `phys` is live and `ci` outlives the call; features were verified
        // present by `missing_features` before we got here.
        Ok(unsafe { instance.create_device(phys, &ci, None) }?)
    }

    /// Free device memory and total, in bytes — `hipMemGetInfo`'s twin.
    ///
    /// `free` is LIVE, via VK_EXT_memory_budget: `DeviceTier::new` gates the tier on
    /// `capacity + 4 GiB headroom <= free`, and substituting the heap SIZE there would
    /// admit a tier that cannot actually fit alongside the compositor and the driver's
    /// own allocations. The failure would then surface as an OOM part-way through
    /// weight loading instead of a clean refusal at startup, which is precisely what
    /// the headroom rule and the sole-tenant guard exist to prevent.
    ///
    /// Falls back to `free == total` only if the extension is absent — and says so,
    /// because a budget guard silently comparing against the heap size is a guard that
    /// always passes.
    pub fn mem_info(&self) -> (usize, usize) {
        let heaps = &self.memprops.memory_heaps[..self.memprops.memory_heap_count as usize];
        let local: Vec<usize> = (0..self.memprops.memory_heap_count as usize)
            .filter(|&i| heaps[i].flags.contains(vk::MemoryHeapFlags::DEVICE_LOCAL))
            .collect();
        let total: u64 = local.iter().map(|&i| heaps[i].size).sum();
        if !self.budget {
            warn!("VK_EXT_memory_budget absent: reporting free = total ({total} B)");
            return (total as usize, total as usize);
        }
        let mut b = vk::PhysicalDeviceMemoryBudgetPropertiesEXT::default();
        let mut p2 = vk::PhysicalDeviceMemoryProperties2::default().push_next(&mut b);
        // SAFETY: `self.phys` is live; the chain outlives the call.
        unsafe {
            self.instance
                .get_physical_device_memory_properties2(self.phys, &mut p2)
        };
        let free: u64 = local
            .iter()
            .map(|&i| b.heap_budget[i].saturating_sub(b.heap_usage[i]))
            .sum();
        (free as usize, total as usize)
    }

    /// Device name, for startup logging and for test output.
    pub fn name(&self) -> String {
        // SAFETY: `self.phys` is live.
        let props = unsafe { self.instance.get_physical_device_properties(self.phys) };
        props.device_name_as_c_str().map_or_else(
            |_| "<unnamed>".to_string(),
            |s| s.to_string_lossy().into_owned(),
        )
    }
}

// ---------------------------------------------------------------------------
// Command recording — HIP default-stream semantics over one command buffer.
// ---------------------------------------------------------------------------

impl Cmd {
    fn new(device: &ash::Device, qfam: u32) -> Result<Self> {
        let pci = vk::CommandPoolCreateInfo::default().queue_family_index(qfam);
        // SAFETY: `device` is live; `pci` outlives the call.
        let pool = unsafe { device.create_command_pool(&pci, None) }?;
        let ai = vk::CommandBufferAllocateInfo::default()
            .command_pool(pool)
            .level(vk::CommandBufferLevel::PRIMARY)
            .command_buffer_count(1);
        // SAFETY: as above; exactly one buffer is requested, so index 0 exists.
        let buf = unsafe { device.allocate_command_buffers(&ai) }?[0];
        // SAFETY: as above.
        let fence = unsafe { device.create_fence(&vk::FenceCreateInfo::default(), None) }?;
        Ok(Self {
            pool,
            buf,
            fence,
            recording: false,
            poisoned: false,
        })
    }
}

impl Gpu {
    /// Append work to the open command buffer, opening one if needed, then serialise
    /// it against whatever comes next. The barrier is what makes a `launch_*` sequence
    /// behave like HIP's default stream — each kernel sees the previous one's writes.
    fn enqueue(&self, f: impl FnOnce(&ash::Device, vk::CommandBuffer)) -> Result<()> {
        let mut cmd = self.cmd.lock().map_err(|_| anyhow!("vk command lock poisoned"))?;
        ensure!(
            !cmd.poisoned,
            "vk command buffer poisoned by an earlier device_sync failure"
        );
        if !cmd.recording {
            let bi = vk::CommandBufferBeginInfo::default()
                .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT);
            // SAFETY: the buffer is not pending — the previous submit was fence-waited
            // and the pool reset in `sync`.
            unsafe { self.device.begin_command_buffer(cmd.buf, &bi) }?;
            cmd.recording = true;
        }
        f(&self.device, cmd.buf);
        let bar = [vk::MemoryBarrier::default()
            .src_access_mask(vk::AccessFlags::SHADER_WRITE)
            .dst_access_mask(vk::AccessFlags::SHADER_READ | vk::AccessFlags::SHADER_WRITE)];
        // SAFETY: recording is open on `cmd.buf`.
        unsafe {
            self.device.cmd_pipeline_barrier(
                cmd.buf,
                vk::PipelineStageFlags::COMPUTE_SHADER,
                vk::PipelineStageFlags::COMPUTE_SHADER,
                vk::DependencyFlags::empty(),
                &bar,
                &[],
                &[],
            );
        }
        Ok(())
    }

    /// Bind, push the constants, dispatch. `push` must be the `#[repr(C)]` mirror of
    /// the shader's `push_constant` block — the ONE place the two sides can disagree,
    /// so each launcher declares its struct next to the launch that uses it.
    fn dispatch<T>(&self, p: &Pipe, push: &T, groups_x: u32) -> Result<()> {
        // The push struct and the pipeline layout are declared in different places and
        // nothing else compares them. `T` must also have NO PADDING — reading padding
        // bytes as `u8` is UB, and a `u64` after an `i32` silently introduces four.
        ensure!(
            size_of::<T>() as u32 == p.push_size,
            "push constant {} B but the pipeline layout declares {} B",
            size_of::<T>(),
            p.push_size
        );
        // SAFETY: `T` is a `#[repr(C)]` struct of scalars with no padding (asserted
        // field-by-field where each push struct is declared), so every byte is
        // initialised and reading it as its own bytes is sound.
        let bytes =
            unsafe { std::slice::from_raw_parts((push as *const T).cast::<u8>(), size_of::<T>()) };
        self.enqueue(|d, cb| {
            // SAFETY: recording is open on `cb`; `p` was built against this device and
            // its layout declares exactly `size_of::<T>()` push-constant bytes.
            unsafe {
                d.cmd_bind_pipeline(cb, vk::PipelineBindPoint::COMPUTE, p.pipe);
                d.cmd_push_constants(cb, p.layout, vk::ShaderStageFlags::COMPUTE, 0, bytes);
                d.cmd_dispatch(cb, groups_x, 1, 1);
            }
        })
    }

    /// Submit whatever is recorded and block until it retires — one join per token,
    /// same contract as `hip::device_sync`. A no-op when nothing was launched.
    pub fn sync(&self) -> Result<()> {
        let mut cmd = self.cmd.lock().map_err(|_| anyhow!("vk command lock poisoned"))?;
        ensure!(
            !cmd.poisoned,
            "vk command buffer poisoned by an earlier device_sync failure"
        );
        if !cmd.recording {
            return Ok(());
        }
        // Poison FIRST, clear only on the success path: every early return below
        // leaves the buffer in a state `vkBeginCommandBuffer` may not be called from,
        // and there are four of them. Opting out of the analysis is cheaper and safer
        // than getting it right per-error-code.
        cmd.poisoned = true;
        // Make the kernels' writes available to the HOST domain, so a readback after
        // the fence is defined without a per-buffer invalidate. Host WRITES need no
        // matching barrier — vkQueueSubmit implies one for anything written before it.
        let bar = [vk::MemoryBarrier::default()
            .src_access_mask(vk::AccessFlags::SHADER_WRITE)
            .dst_access_mask(vk::AccessFlags::HOST_READ)];
        let bufs = [cmd.buf];
        let si = [vk::SubmitInfo::default().command_buffers(&bufs)];
        // SAFETY: recording is open; the fence is unsignalled (reset below on every
        // path that signals it); nothing else touches this queue (see the Sync impl).
        unsafe {
            self.device.cmd_pipeline_barrier(
                cmd.buf,
                vk::PipelineStageFlags::COMPUTE_SHADER,
                vk::PipelineStageFlags::HOST,
                vk::DependencyFlags::empty(),
                &bar,
                &[],
                &[],
            );
            self.device.end_command_buffer(cmd.buf)?;
            cmd.recording = false;
            self.device.queue_submit(self.queue, &si, cmd.fence)?;
            self.device.wait_for_fences(&[cmd.fence], true, u64::MAX)?;
            self.device.reset_fences(&[cmd.fence])?;
            self.device
                .reset_command_pool(cmd.pool, vk::CommandPoolResetFlags::empty())?;
        }
        cmd.poisoned = false; // every step succeeded; the buffer is initial again
        Ok(())
    }
}

/// Block until all launched kernels retire — one join per token. `hip::device_sync`'s
/// twin, and the same contract: device pointers handed to a `launch_*` must stay valid
/// until this returns.
pub fn device_sync() -> Result<()> {
    gpu()?.sync()
}

// ---------------------------------------------------------------------------
// Pipelines
// ---------------------------------------------------------------------------

impl Pipes {
    fn new(device: &ash::Device) -> Result<Self> {
        Ok(Self {
            gemv_f32: Pipe::new(
                device,
                include_bytes!(concat!(env!("OUT_DIR"), "/gemv_f32.spv")),
                size_of::<GemvF32Push>() as u32,
            )?,
        })
    }
}

impl Pipe {
    fn new(device: &ash::Device, spv: &[u8], push_size: u32) -> Result<Self> {
        let words = ash::util::read_spv(&mut std::io::Cursor::new(spv))?;
        let smci = vk::ShaderModuleCreateInfo::default().code(&words);
        // SAFETY: `device` is live; `words` outlives the call.
        let module = unsafe { device.create_shader_module(&smci, None) }?;
        let ranges = [vk::PushConstantRange::default()
            .stage_flags(vk::ShaderStageFlags::COMPUTE)
            .offset(0)
            .size(push_size)];
        let plci = vk::PipelineLayoutCreateInfo::default().push_constant_ranges(&ranges);
        // SAFETY: as above. No descriptor-set layouts: every buffer is a device address.
        let layout = unsafe { device.create_pipeline_layout(&plci, None) }?;
        // Pin the subgroup to WAVE and require FULL subgroups, so the shaders' fixed
        // 32-lane shuffle ladder is a driver-enforced fact rather than an assumption.
        let mut req = vk::PipelineShaderStageRequiredSubgroupSizeCreateInfo::default()
            .required_subgroup_size(WAVE);
        let stage = vk::PipelineShaderStageCreateInfo::default()
            .stage(vk::ShaderStageFlags::COMPUTE)
            .module(module)
            .name(c"main")
            .flags(vk::PipelineShaderStageCreateFlags::REQUIRE_FULL_SUBGROUPS)
            .push_next(&mut req);
        let ci = [vk::ComputePipelineCreateInfo::default()
            .stage(stage)
            .layout(layout)];
        // SAFETY: as above.
        let pipes = unsafe { device.create_compute_pipelines(vk::PipelineCache::null(), &ci, None) }
            .map_err(|(_, e)| e)?;
        // SAFETY: the module is only needed while the pipeline is being created.
        unsafe { device.destroy_shader_module(module, None) };
        let pipe = *pipes.first().ok_or_else(|| anyhow!("no compute pipeline created"))?;
        Ok(Self {
            layout,
            pipe,
            push_size,
        })
    }
}

// ---------------------------------------------------------------------------
// Buffers
// ---------------------------------------------------------------------------

/// One device allocation: a `VkBuffer` bound to its own `VkDeviceMemory`, permanently
/// host-mapped, exposed to the kernels by its DEVICE ADDRESS.
///
/// This is the primitive `device.rs`'s `DeviceBuf`/`DeviceTier`/`VmmBuf` are built
/// from. On Strix Halo host RAM *is* GPU memory, so the same allocation is both
/// device-local (full bandwidth) and host-writable in place — the Vulkan spelling of
/// what `kernels/vmm.hip` does with HIP VMM.
pub struct Buf {
    buf: vk::Buffer,
    mem: vk::DeviceMemory,
    addr: u64,
    host: *mut u8,
    len: usize,
}

impl Buf {
    pub fn new(len: usize) -> Result<Self> {
        ensure!(len > 0, "Buf::new(0): Vulkan rejects a zero-sized buffer");
        let g = gpu()?;
        let bci = vk::BufferCreateInfo::default()
            .size(len as u64)
            .usage(
                vk::BufferUsageFlags::STORAGE_BUFFER
                    | vk::BufferUsageFlags::SHADER_DEVICE_ADDRESS
                    | vk::BufferUsageFlags::TRANSFER_SRC
                    | vk::BufferUsageFlags::TRANSFER_DST,
            )
            .sharing_mode(vk::SharingMode::EXCLUSIVE);
        // SAFETY: the device is live; `bci` outlives the call.
        let buf = unsafe { g.device.create_buffer(&bci, None) }?;
        // Allocation failure is RECOVERABLE here — the engine hits it during weight
        // residency and reports it — so every `?` below must undo what came before.
        // Leaking a VkBuffer per attempt would exhaust handles across a retry while
        // still reporting OOM, which reads as the wrong bug.
        match Self::finish(g, buf, len) {
            Ok(b) => Ok(b),
            Err(e) => {
                // SAFETY: `buf` is live, unbound, and referenced by nothing.
                unsafe { g.device.destroy_buffer(buf, None) };
                Err(e)
            }
        }
    }

    fn finish(g: &'static Gpu, buf: vk::Buffer, len: usize) -> Result<Self> {
        // SAFETY: `buf` was just created on this device.
        let req = unsafe { g.device.get_buffer_memory_requirements(buf) };
        let want = vk::MemoryPropertyFlags::DEVICE_LOCAL
            | vk::MemoryPropertyFlags::HOST_VISIBLE
            | vk::MemoryPropertyFlags::HOST_COHERENT;
        let types = &g.memprops.memory_types[..g.memprops.memory_type_count as usize];
        let idx = types
            .iter()
            .enumerate()
            .position(|(i, t)| {
                req.memory_type_bits & (1 << i) != 0 && t.property_flags.contains(want)
            })
            .ok_or_else(|| {
                anyhow!("no DEVICE_LOCAL|HOST_VISIBLE|HOST_COHERENT memory type for a {len}B buffer")
            })? as u32;
        let mut flags =
            vk::MemoryAllocateFlagsInfo::default().flags(vk::MemoryAllocateFlags::DEVICE_ADDRESS);
        let ai = vk::MemoryAllocateInfo::default()
            .allocation_size(req.size)
            .memory_type_index(idx)
            .push_next(&mut flags);
        // SAFETY: as above.
        let mem = unsafe { g.device.allocate_memory(&ai, None) }?;
        let bind_and_map = || -> Result<*mut u8> {
            // SAFETY: `mem` was allocated for `buf`'s requirements, nothing is bound
            // yet, and the mapping covers the whole allocation.
            unsafe {
                g.device.bind_buffer_memory(buf, mem, 0)?;
                Ok(g.device
                    .map_memory(mem, 0, req.size, vk::MemoryMapFlags::empty())?
                    as *mut u8)
            }
        };
        let host = match bind_and_map() {
            Ok(h) => h,
            Err(e) => {
                // SAFETY: `mem` is live and (on the bind-failure path) unbound; the
                // caller destroys `buf`.
                unsafe { g.device.free_memory(mem, None) };
                return Err(e);
            }
        };
        let info = vk::BufferDeviceAddressInfo::default().buffer(buf);
        // SAFETY: `buf` was created with SHADER_DEVICE_ADDRESS and is bound.
        let addr = unsafe { g.device.get_buffer_device_address(&info) };
        Ok(Self {
            buf,
            mem,
            addr,
            host,
            len,
        })
    }

    /// The buffer's DEVICE address, shaped as a pointer so the `launch_*` signatures
    /// match `hip.rs`'s exactly.
    ///
    /// **Not dereferenceable on the host.** Under HIP unified addressing the host and
    /// device see one address; under Vulkan they do not. Host access goes through
    /// [`Buf::write_at`] / [`Buf::read_into`], and the engine only ever passes these
    /// values through to kernels — which is why the swap costs `gpu.rs` nothing.
    pub fn ptr(&self) -> *const u8 {
        self.addr as *const u8
    }
    pub fn ptr_mut(&mut self) -> *mut u8 {
        self.addr as *mut u8
    }

    /// Host-write `bytes` at byte offset `off`. HOST_COHERENT, and `vkQueueSubmit`
    /// implies the host-write barrier, so no flush and no `hipMemcpy` — the write is
    /// visible to any kernel submitted after it returns.
    pub fn write_at(&mut self, off: usize, bytes: &[u8]) -> Result<()> {
        // checked_add, not `off + len`: this is a SAFE fn, and in release `off` near
        // usize::MAX would wrap the sum to something small, pass the check, and let
        // copy_nonoverlapping write outside the mapping.
        ensure!(
            off.checked_add(bytes.len()).is_some_and(|e| e <= self.len),
            "write_at {off}+{} > buf len {}",
            bytes.len(),
            self.len
        );
        // SAFETY: the mapping covers `self.len`; `off+len` is within it (checked).
        unsafe { std::ptr::copy_nonoverlapping(bytes.as_ptr(), self.host.add(off), bytes.len()) };
        Ok(())
    }

    /// Read the first `len` bytes back into `out` (cleared, then refilled). Call after
    /// a [`device_sync`] — that is where the kernels' writes are made host-visible.
    pub fn read_into(&self, out: &mut Vec<u8>, len: usize) -> Result<()> {
        ensure!(len <= self.len, "read_into {len} > buf len {}", self.len);
        out.clear();
        out.reserve(len);
        // SAFETY: the mapping covers `self.len >= len`; `out` owns `len` reserved bytes.
        unsafe {
            std::ptr::copy_nonoverlapping(self.host, out.as_mut_ptr(), len);
            out.set_len(len);
        }
        Ok(())
    }
}

impl Drop for Buf {
    fn drop(&mut self) {
        let Ok(g) = gpu() else { return };
        // Flush first. Every buffer reaches the shader as a bare device address baked
        // into a push constant at RECORD time, so a dispatch recorded before this drop
        // still references these bytes — and because the address carries no object
        // identity, not even a validation layer could catch the use-after-free. A no-op
        // when nothing is recorded, which is the common case.
        if let Err(e) = g.sync() {
            warn!("Buf::drop: flush failed, freeing anyway: {e:#}");
        }
        // SAFETY: all three handles came from this device and are released once. The
        // caller's contract (see `device_sync`) is that no kernel still references them.
        unsafe {
            g.device.unmap_memory(self.mem);
            g.device.destroy_buffer(self.buf, None);
            g.device.free_memory(self.mem, None);
        }
    }
}

// ---------------------------------------------------------------------------
// Kernel launchers — the `hip.rs` surface, one fn per ported kernel.
// ---------------------------------------------------------------------------

/// Declare a `push_constant` mirror struct, with both of its invariants checked AT
/// COMPILE TIME rather than left as rules a porter has to remember at kernel 11 of 16:
///
/// - **No padding.** `dispatch` reads the struct as its own bytes; padding bytes are
///   uninitialised, and reading them as `u8` is UB. std430 would also place the
///   shader's fields differently than a padded Rust struct does, so the values would
///   silently land in the wrong slots. A `u64` after an `i32` introduces four bytes of
///   it, which is one field reorder away at every future launcher.
/// - **Fits the guaranteed budget.** 128 bytes is all Vulkan promises. Exceeding it is
///   the "push-constant budget" risk in docs/VULKAN.md; this makes it a build error
///   instead of a device-dependent surprise, so the params-buffer fallback gets built
///   the day it is actually needed and not before.
///
/// Order fields largest-first (8-byte device addresses, then 4-byte scalars) and the
/// no-padding check is satisfied naturally.
macro_rules! push_struct {
    ($(#[$m:meta])* $name:ident { $($f:ident: $t:ty),+ $(,)? }) => {
        $(#[$m])*
        #[repr(C)]
        struct $name { $($f: $t),+ }
        const _: () = assert!(
            size_of::<$name>() == 0 $(+ size_of::<$t>())+,
            concat!(stringify!($name), " has padding: reorder fields largest-first"),
        );
        const _: () = assert!(
            size_of::<$name>() <= 128,
            concat!(stringify!($name), " exceeds the 128-byte guaranteed push budget"),
        );
    };
}

push_struct! {
    /// Mirror of `gemv_f32.comp`'s `push_constant` block. std430: three 8-byte buffer
    /// references then two ints — 32 bytes.
    GemvF32Push {
        x: u64,
        w: u64,
        y: u64,
        o_dim: i32,
        i_dim: i32,
    }
}

/// f32 GEMV `y = W·x` (the MoE router gate).
///
/// # Safety
/// `x`, `w` and `y` must be DEVICE ADDRESSES of live [`Buf`] regions holding `i_dim`,
/// `o_dim·i_dim` and `o_dim` f32 respectively, and must stay live until the next
/// [`device_sync`].
pub unsafe fn launch_gemv_f32(
    x: *const f32,
    w: *const f32,
    o_dim: usize,
    i_dim: usize,
    y: *mut f32,
) -> Result<()> {
    ensure!(o_dim > 0 && i_dim > 0, "gemv_f32: argument guard rejected");
    let g = gpu()?;
    let push = GemvF32Push {
        x: x as u64,
        w: w as u64,
        y: y as u64,
        o_dim: o_dim as i32,
        i_dim: i_dim as i32,
    };
    g.dispatch(
        &g.pipes.gemv_f32,
        &push,
        o_dim.div_ceil(ROWS_PER_BLOCK as usize) as u32,
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn context_initialises() {
        let g = gpu().expect("vulkan init");
        let (free, total) = g.mem_info();
        println!(
            "\nVULKAN device: {} — {:.1} GiB device-local — validation layer: {}\n",
            g.name(),
            total as f64 / (1u64 << 30) as f64,
            if g.validation() { "ON" } else { "OFF (unvalidated!)" }
        );
        assert!(total > 0, "no DEVICE_LOCAL heap");
        // NOT `assert_eq!(free, total)`. That is what the stub used to return, and
        // asserting it encoded a bug as intent — `DeviceTier::new` gates the resident
        // tier on `free`, so free==total makes that guard always pass. The real
        // property is that free is a live figure below the heap size.
        assert!(free > 0 && free <= total, "free {free} total {total}");
        println!("VULKAN free: {:.1} GiB", free as f64 / (1u64 << 30) as f64);
        // Second call must hand back the same context, not build another.
        assert!(std::ptr::eq(g, gpu().expect("cached")));
    }
}
